/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vurcon_machine.glb -o src/components/Ferrotall/VurconMachine2.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/vurcon_machine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Maquina.geometry} material={materials.Colores_Vurcon} scale={[1, 0.866, 0.787]} />
    </group>
  )
}

useGLTF.preload('/models/vurcon_machine.glb')
