/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/navi_office.glb -o src/components/NaviOffice/NaviOffice.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function NaviOffice(props) {
  const { nodes, materials } = useGLTF('/models/navi_office.glb')
  return (
    <RigidBody type="fixed" colliders="trimesh">
    
    <group {...props} dispose={null}>
      <spotLight intensity={1.571} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#ffefe6" position={[0.007, 0.359, -1.4]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.233, 0.294, 0.042]} />
      <pointLight intensity={4.703} decay={2} position={[0.058, 0.451, 0.246]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.446, 0.794, 1]} />
      <pointLight intensity={1.703} decay={2} position={[-0.831, 0.417, 0.676]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.446, 0.794, 1]} />
      <pointLight intensity={1.703} decay={2} position={[0.899, 0.383, 0.676]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.446, 0.794, 1]} />
      <spotLight intensity={1.571} angle={Math.PI / 1} penumbra={0.15} decay={2} color="#ffefe6" position={[0.007, 0.359, -0.604]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.233, 0.294, 0.042]} />
      <mesh geometry={nodes.marco_izq.geometry} material={materials.Colores_navi} position={[-0.616, 0.15, -0.011]} scale={[0.234, 0.216, 0.036]} />
      <mesh geometry={nodes.marco_der.geometry} material={materials.Colores_navi} position={[0.609, 0.15, -0.011]} scale={[0.234, 0.216, 0.036]} />
      <mesh geometry={nodes.BAJO_DE_PARED_IZQ_RECIBIDOR.geometry} material={materials.Colores_navi} position={[0.933, 0.003, 0.671]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.059, -0.009, -0.669]} />
      <mesh geometry={nodes.BAJO_DE_PARED_RECIBIDOR.geometry} material={materials.Colores_navi} position={[-0.935, 0.007, 0.672]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.059, -0.015, -0.671]} />
      <mesh geometry={nodes.MESA_RECEPCION.geometry} material={materials.Colores_navi} position={[0, 0.041, 0.245]} scale={[0.287, 0.049, 0.035]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ001.geometry} material={materials.Colores_navi} position={[-0.996, 0.273, 1.111]} rotation={[-Math.PI, 0, 0]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ002.geometry} material={materials.Colores_navi} position={[-0.996, 0.273, 0.68]} rotation={[-Math.PI, 0, 0]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ003.geometry} material={materials.Colores_navi} position={[-0.996, 0.273, 0.253]} rotation={[-Math.PI, 0, 0]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ004.geometry} material={materials.Colores_navi} position={[0.995, 0.273, 0.251]} rotation={[0, 0.003, -Math.PI]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ005.geometry} material={materials.Colores_navi} position={[0.997, 0.273, 0.682]} rotation={[0, 0.003, -Math.PI]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MARCO_RECIBIDOR_IZQ006.geometry} material={materials.Colores_navi} position={[0.998, 0.273, 1.11]} rotation={[0, 0.003, -Math.PI]} scale={[-0.003, -0.092, -0.168]} />
      <mesh geometry={nodes.MESA_REUNIONES.geometry} material={materials.Colores_navi} position={[-0.008, 0.096, -0.997]} scale={[0.277, 0.007, 0.657]} />
      <mesh geometry={nodes.NIVELADOR_DERECHA.geometry} material={materials.Colores_navi} position={[0.997, 0.001, -0.015]} scale={-0.012} />
      <mesh geometry={nodes.NIVELADOR_FONDO.geometry} material={materials.Colores_navi} position={[0.997, 0.001, -1.999]} rotation={[0, Math.PI / 2, 0]} scale={-0.012} />
      <mesh geometry={nodes.NIVELADOR_IZQ.geometry} material={materials.Colores_navi} position={[-1.002, 0.001, -0.015]} scale={-0.012} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0.003, 0.302, 0.006]} rotation={[Math.PI / 2, 0, 0]} scale={0.11} />
      <group position={[-0.002, 0.288, -0.009]} rotation={[0.003, 0.001, 3.139]} scale={[0.209, 0.112, 0.004]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Colores_navi} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Colores_navi} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Colores_navi} position={[-0.004, -0.003, 0.178]} scale={[0.382, 0.007, 0.186]} />
      <mesh geometry={nodes.cajonera_V2.geometry} material={materials.Colores_navi} position={[-0.001, -0.002, -0.084]} rotation={[Math.PI, 0, Math.PI]} scale={[1.081, 0.185, 0.078]} />
      <mesh geometry={nodes.Maceta_V1.geometry} material={materials.Colores_navi} position={[0.285, 0.145, -0.048]} scale={0.061} />
      <mesh geometry={nodes.Maceta_V1001.geometry} material={materials.Colores_navi} position={[-0.287, 0.145, -0.048]} scale={0.061} />
      <mesh geometry={nodes.Silla_V2.geometry} material={materials.Colores_navi} position={[-0.336, -0.001, -1.305]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={0.101} />
      <mesh geometry={nodes.Silla_V001.geometry} material={materials.Colores_navi} position={[-0.336, -0.001, -0.597]} rotation={[0, 1.569, 0]} scale={0.101} />
      <mesh geometry={nodes.Silla_V003.geometry} material={materials.Colores_navi} position={[-0.336, -0.001, -0.968]} rotation={[-Math.PI, 1.556, -Math.PI]} scale={0.101} />
      <mesh geometry={nodes.Silla_V004.geometry} material={materials.Colores_navi} position={[0.316, -0.001, -0.608]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.101} />
      <mesh geometry={nodes.Silla_V005.geometry} material={materials.Colores_navi} position={[0.341, -0.001, -1.316]} rotation={[Math.PI, -1.534, Math.PI]} scale={0.101} />
      <mesh geometry={nodes.Silla_V006.geometry} material={materials.Colores_navi} position={[0.328, -0.001, -0.945]} rotation={[Math.PI, -1.55, Math.PI]} scale={0.101} />
      <mesh geometry={nodes.Silla_V007.geometry} material={materials.Colores_navi} position={[0.006, -0.001, -1.708]} rotation={[0, 0.008, 0]} scale={0.101} />
      <mesh geometry={nodes.Silla_V008.geometry} material={materials.Colores_navi} position={[0.006, -0.005, 0.15]} rotation={[0, 0.008, 0]} scale={0.101} />
      <mesh geometry={nodes.Maceta_V3.geometry} material={materials.Colores_navi} position={[0.003, 0.098, -1.002]} scale={0.079} />
      <mesh geometry={nodes.Maceta_V3001.geometry} material={materials.Colores_navi} position={[0.003, 0.098, -1.002]} scale={0.079} />
      <mesh geometry={nodes.Computadora_V2.geometry} material={materials.Colores_navi} position={[0.007, 0.09, 0.29]} rotation={[-Math.PI, 0.023, -Math.PI]} scale={0.103} />
      <mesh geometry={nodes.Libro_individual.geometry} material={materials.Colores_navi} position={[0.283, 0.054, -0.077]} rotation={[Math.PI, 0, Math.PI]} scale={0.063} />
      <mesh geometry={nodes.Archivador.geometry} material={materials.Colores_navi} position={[-0.307, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador001.geometry} material={materials.Colores_navi} position={[-0.293, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador002.geometry} material={materials.Colores_navi} position={[-0.278, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador003.geometry} material={materials.Colores_navi} position={[-0.263, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador004.geometry} material={materials.Colores_navi} position={[-0.248, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador005.geometry} material={materials.Colores_navi} position={[-0.233, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador006.geometry} material={materials.Colores_navi} position={[-0.218, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador007.geometry} material={materials.Colores_navi} position={[-0.203, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador008.geometry} material={materials.Colores_navi} position={[-0.189, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador009.geometry} material={materials.Colores_navi} position={[-0.174, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador010.geometry} material={materials.Colores_navi} position={[-0.159, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Archivador011.geometry} material={materials.Colores_navi} position={[-0.144, 0.051, -0.078]} rotation={[Math.PI, 0, Math.PI]} scale={0.047} />
      <mesh geometry={nodes.Libros_Conjunto_V1.geometry} material={materials.Colores_navi} position={[0.288, 0.099, -0.069]} rotation={[Math.PI, 0, Math.PI]} scale={0.052} />
      <mesh geometry={nodes.Libros_Conjunto_V1001.geometry} material={materials.Colores_navi} position={[0.245, 0.099, -0.069]} rotation={[Math.PI, 0, Math.PI]} scale={0.052} />
      <mesh geometry={nodes.Libros_Conjunto_V2.geometry} material={materials.Colores_navi} position={[-0.295, 0.099, -0.07]} rotation={[Math.PI, 0, Math.PI]} scale={0.043} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Colores_navi} position={[-0.003, 0.001, -1.063]} scale={[0.511, 0.89, 0.751]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} position={[-0.938, 0.364, -0.003]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[0.927, 0.358, -0.018]} />
      <mesh geometry={nodes.Planta_V1022.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 1.246]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1023.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 0.098]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1024.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 0.313]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1025.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 1.024]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1026.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 0.795]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1027.geometry} material={materials.Colores_navi} position={[-0.925, -0.033, 0.578]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1028.geometry} material={materials.Colores_navi} position={[0.002, 0.106, -1.002]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1029.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 1.246]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1030.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 0.098]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1031.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 0.313]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1032.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 1.024]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1033.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 0.795]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1034.geometry} material={materials.Colores_navi} position={[0.926, -0.033, 0.578]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1035.geometry} material={materials.Colores_navi} position={[0.282, 0.12, -0.046]} rotation={[-2.858, -0.538, -3.029]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Planta_V1036.geometry} material={materials.Colores_navi} position={[-0.298, 0.12, -0.046]} rotation={[-2.843, -0.496, -3.013]} scale={[0.26, 0.037, 745174.5]} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Colores_navi} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.001']} />
    </group>
        </RigidBody>
    
  )
}

export default NaviOffice
useGLTF.preload('/models/navi_office.glb')
