/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/character.glb -o src/components/Avatar.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Avatar({ animation = "LOLO_Animation_Idle", pause = false, ...props }) {
  const group = useRef();
  
    // Cargar el modelo y animaciones
    const { scene, animations } = useGLTF('/models/character.glb');
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    const { actions } = useAnimations(animations, group);
  
    useEffect(() => {
      if (actions) {
        // Pausar todas las animaciones inicialmente
        Object.values(actions).forEach((action) => action.stop());
      }
    }, [actions]);
    useEffect(() => {
      console.log(actions)
    }, [actions]);
  

    useEffect(() => {
      if (actions && actions[animation]) {
        console.log("Acción encontrada:", actions[animation]);
        console.log("Intentando reproducir la animación...");
    
        // Detenemos todas las acciones activas con un fade out suave
        Object.values(actions).forEach((action) => {
          if (action.isRunning()) {
            action.fadeOut(0.5); // Duración de la transición
          }
        });
    
        // Reproducimos la nueva animación con un fade in suave
        const newAction = actions[animation];
        newAction.reset().fadeIn(0.1).play(); // Duración de la transición
    
        console.log("Estado de la animación después de play:", newAction.isRunning());
      } else {
        console.warn(`No se encontró la animación: ${animation}`);
      }
    }, [animation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Boca_select">
          <primitive object={nodes.Bone} />
        </group>
        <group name="Ojo_der_select">
          <primitive object={nodes.Bone_1} />
        </group>
        <group name="Ojo_izq_select">
          <primitive object={nodes.Bone_2} />
        </group>
        <group name="esqueleto_corbata" position={[-0.024, 0.732, 0.291]} rotation={[-0.519, 0, 0]} scale={0.233}>
          <primitive object={nodes.Bone_3} />
          <skinnedMesh name="corbata" geometry={nodes.corbata.geometry} material={materials['Material.001']} skeleton={nodes.corbata.skeleton} />
        </group>
        <group name="circulo_movimiento_general" position={[-0.024, 0.732, 0.291]} rotation={[-0.519, 0, 0]} scale={0.233} />
        <group name="rig">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_arms_polel} />
          <primitive object={nodes.c_arms_poler} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.c_hand_ikr} />
          <primitive object={nodes.c_hand_ikl} />
          <primitive object={nodes.root_refx} />
          <primitive object={nodes.Ctrl_Master} />
          <group name="cabeza004">
            <skinnedMesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Cara_Ojo_izquierda} skeleton={nodes.Cube005.skeleton} />
            <skinnedMesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.Cara_Ojo_derecho} skeleton={nodes.Cube005_1.skeleton} />
            <skinnedMesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.Cara_boca} skeleton={nodes.Cube005_2.skeleton} />
            <skinnedMesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.cabeza} skeleton={nodes.Cube005_3.skeleton} />
          </group>
          <group name="cuerpo001">
            <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.cuerpo_cabeza} skeleton={nodes.Cylinder004.skeleton} />
            <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.cuerpo_torzo} skeleton={nodes.Cylinder004_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Avatar;
useGLTF.preload('/models/character.glb')
