/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/character.glb -o src/components/Avatar.jsx -r public 
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

// Se envuelve el componente en React.memo para evitar re-renderizados innecesarios
const Avatar = React.memo(({ animation = "LOLO_Animation_Idle", pause = false, ...props }) => {
  const group = useRef();

  // Carga el modelo y sus animaciones; useGLTF cachea internamente la carga
  const { scene, animations } = useGLTF('/models/character.glb');

  // Memoriza el clon del modelo para que solo se realice cuando 'scene' cambie
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  // Obtiene nodos y materiales del clon
  const { nodes, materials } = useGraph(clone);

  // Configura las animaciones usando el grupo como referencia
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // Se detienen todas las animaciones inicialmente para evitar ejecuciones innecesarias
      Object.values(actions).forEach((action) => action.stop());
    }
  }, [actions]);

  useEffect(() => {
    if (actions && actions[animation]) {
      // Detenemos todas las acciones activas con un fade out suave
      Object.values(actions).forEach((action) => {
        if (action.isRunning()) {
          action.fadeOut(0.5); // Duración de la transición
        }
      });
  
      // Reproducimos la nueva animación con un fade in suave
      const newAction = actions[animation];
      let tieAction = []
      if(animation === "LOLO_Animation_Idle"){
         tieAction = actions["Corbata_Animation_Idle"]
      }else if(animation === "LOLO_Animation_Walk"){
         tieAction = actions["Corbata_Animation_walk"]
      }
      newAction.reset().fadeIn(0.1).play(); // Duración de la transición
      tieAction.reset().fadeIn(0.1).play(); // Duración de la transición
    }
  }, [animation, actions]);

  return (
    <group ref={group} {...props} dispose={null} name='chatbot-body'>
      <group name="Scene">
        <group name="Boca_select">
          <primitive object={nodes.Bone} />
        </group>
        <group name="Ojo_der_select">
          <primitive object={nodes.Bone_1} />
        </group>
        <group name="Ojo_izq_select">
          <primitive object={nodes.Bone_2} />
        </group>
        <group name="esqueleto_corbata" position={[-0.024, 0.732, 0.291]} rotation={[-0.519, 0, 0]} scale={0.233}>
          <primitive object={nodes.Bone_3} />
          <skinnedMesh name="corbata" geometry={nodes.corbata.geometry} material={materials['Material.001']} skeleton={nodes.corbata.skeleton} />
        </group>
        <group name="circulo_movimiento_general" position={[-0.024, 0.732, 0.291]} rotation={[-0.519, 0, 0]} scale={0.233} />
        <group name="rig">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_arms_polel} />
          <primitive object={nodes.c_arms_poler} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.c_hand_ikr} />
          <primitive object={nodes.c_hand_ikl} />
          <primitive object={nodes.root_refx} />
          <primitive object={nodes.Ctrl_Master} />
          <group name="cabeza004">
            <skinnedMesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Cara_Ojo_izquierda} skeleton={nodes.Cube005.skeleton} />
            <skinnedMesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.Cara_Ojo_derecho} skeleton={nodes.Cube005_1.skeleton} />
            <skinnedMesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.Cara_boca} skeleton={nodes.Cube005_2.skeleton} />
            <skinnedMesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.cabeza} skeleton={nodes.Cube005_3.skeleton} />
          </group>
          <group name="cuerpo001">
            <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.cuerpo_cabeza} skeleton={nodes.Cylinder004.skeleton} />
            <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.cuerpo_torzo} skeleton={nodes.Cylinder004_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  );
});

export default Avatar;
useGLTF.preload('/models/character.glb')
