/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/base.glb -o src/components/Base.jsx -r public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier';

export function Base(props) {
  const { scene } = useGLTF('/models/base.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
      <RigidBody type="fixed" name="ground" colliders="trimesh">
    
    <group {...props} dispose={null}>
      <group position={[0.177, 0, 0]} scale={0.013}>
        <primitive object={nodes.Bone} />
      </group>
      <group position={[0, 0.102, 0]} scale={[1.72, 24.125, 1.72]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Material} />
      </group>
      <group position={[0, 0.102, 0]} scale={[1.72, 24.125, 1.72]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0, 0.013, 0]} scale={6.242} />
      <group position={[-3.015, 0.045, 0.008]} rotation={[Math.PI, -1.486, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-2.202, 0.044, 2.051]} rotation={[0, -0.911, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-0.024, 0.044, 3.038]} rotation={[0, -0.094, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[2.152, 0.044, -2.131]} rotation={[-Math.PI, 0.901, -Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-1.999, 0.043, -2.283]} rotation={[Math.PI, -0.571, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[2.08, 0.043, 2.2]} rotation={[0, 0.679, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[2.155, 0.279, -2.127]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.377, 0.002, 0.377]} />
      <group position={[1.555, 0.187, -1.537]} rotation={[0.357, -0.731, 0.244]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[1.482, 0.185, 1.607]} rotation={[2.778, -0.749, 2.888]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-0.032, 0.187, 2.195]} rotation={[2.878, -0.023, 3.135]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-1.595, 0.187, 1.472]} rotation={[2.773, 0.764, -2.88]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-2.176, 0.187, -0.009]} rotation={[1.695, 1.305, -1.699]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-1.471, 0.187, -1.624]} rotation={[0.335, 0.658, -0.21]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.007']} position={[-0.003, 0.103, 0.017]} rotation={[-Math.PI, 0.413, -Math.PI]} scale={[-0.884, -0.053, -0.884]} />
      <mesh geometry={nodes.Torus003.geometry} material={materials['Material.007']} position={[0.028, -0.186, 0.023]} rotation={[0, -0.037, 0]} scale={1.336} />
      <mesh geometry={nodes.stone003.geometry} material={materials.Mat_tree} position={[0.057, 0.82, -0.243]} scale={0.088} />
      <mesh geometry={nodes.stone001.geometry} material={materials.Mat_tree} position={[0.089, 0.837, -0.185]} rotation={[0, -1.29, 0]} scale={0.059} />
      <mesh geometry={nodes.stone002.geometry} material={materials.Mat_tree} position={[0.047, 0.851, -0.168]} rotation={[0.497, -1.29, 0]} scale={0.059} />
      <mesh geometry={nodes.stone004.geometry} material={materials.Mat_tree} position={[-0.012, 0.687, 0.172]} rotation={[0, 0.943, 0]} scale={0.088} />
      <mesh geometry={nodes.stone005.geometry} material={materials.Mat_tree} position={[0.055, 0.704, 0.181]} rotation={[0, -0.347, 0]} scale={0.059} />
      <mesh geometry={nodes.stone006.geometry} material={materials.Mat_tree} position={[0.044, 0.719, 0.225]} rotation={[0.143, -0.376, -0.428]} scale={0.059} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[-0.003, 0.129, 0]} scale={0.806} />
      <mesh geometry={nodes.branch4002.geometry} material={materials.color_Palette} position={[0.46, 0.134, 0.554]} rotation={[0, -1.241, 0]} scale={0.093} />
      <mesh geometry={nodes.branch4004.geometry} material={materials.color_Palette} position={[-0.257, 0.134, 0.636]} rotation={[0, -1.491, 0]} scale={0.093} />
      <mesh geometry={nodes.branch4006.geometry} material={materials.color_Palette} position={[-0.663, 0.134, 0.119]} rotation={[-Math.PI, 0.472, -Math.PI]} scale={0.093} />
      <mesh geometry={nodes.branch4008.geometry} material={materials.color_Palette} position={[-0.41, 0.134, -0.452]} rotation={[-Math.PI, 0.982, -Math.PI]} scale={0.093} />
      <mesh geometry={nodes.branch4010.geometry} material={materials.color_Palette} position={[0.271, 0.134, -0.593]} rotation={[0, 0.391, 0]} scale={0.093} />
      <mesh geometry={nodes.grass007.geometry} material={materials['color_Palette.001']} position={[0.674, 0.111, -0.735]} rotation={[3.141, 0.663, -3.133]} scale={0.053} />
      <mesh geometry={nodes.grass017.geometry} material={materials['color_Palette.001']} position={[1.429, 0.111, -1.194]} rotation={[-Math.PI, 0.998, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass018.geometry} material={materials['color_Palette.001']} position={[1.22, 0.111, -1.406]} rotation={[-Math.PI, 0.998, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass019.geometry} material={materials['color_Palette.001']} position={[0.719, 0.111, -0.446]} rotation={[-Math.PI, 0.998, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass020.geometry} material={materials['color_Palette.001']} position={[0.719, 0.111, -0.555]} rotation={[Math.PI, -1.462, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass021.geometry} material={materials['color_Palette.001']} position={[0.823, 0.111, -0.478]} rotation={[Math.PI, -0.27, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass022.geometry} material={materials['color_Palette.001']} position={[0.44, 0.111, -0.736]} rotation={[-Math.PI, 1.386, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass023.geometry} material={materials['color_Palette.001']} position={[0.569, 0.111, -0.736]} rotation={[-Math.PI, 0.377, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass024.geometry} material={materials['color_Palette.001']} position={[0.664, 0.111, -0.808]} rotation={[-Math.PI, 1.456, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass025.geometry} material={materials['color_Palette.001']} position={[0.752, 0.111, -0.697]} rotation={[Math.PI, -0.069, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass026.geometry} material={materials['color_Palette.001']} position={[0.558, 0.111, -0.979]} rotation={[3.141, -0.012, -3.133]} scale={0.053} />
      <mesh geometry={nodes.grass027.geometry} material={materials['color_Palette.001']} position={[1.044, 0.111, -0.626]} rotation={[-Math.PI, 0.998, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass028.geometry} material={materials['color_Palette.001']} position={[-0.918, 0.111, -0.806]} rotation={[Math.PI, -0.591, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass029.geometry} material={materials['color_Palette.001']} position={[-0.512, 0.111, -0.694]} rotation={[Math.PI, -0.591, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass030.geometry} material={materials['color_Palette.001']} position={[-0.621, 0.111, -0.692]} rotation={[0, -0.091, 0]} scale={0.053} />
      <mesh geometry={nodes.grass031.geometry} material={materials['color_Palette.001']} position={[-0.546, 0.111, -0.797]} rotation={[0, -1.283, 0]} scale={0.053} />
      <mesh geometry={nodes.grass032.geometry} material={materials['color_Palette.001']} position={[-0.797, 0.111, -0.41]} rotation={[Math.PI, -0.204, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass033.geometry} material={materials['color_Palette.001']} position={[-0.799, 0.111, -0.538]} rotation={[Math.PI, -1.212, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass034.geometry} material={materials['color_Palette.001']} position={[-0.873, 0.111, -0.632]} rotation={[Math.PI, -0.133, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass035.geometry} material={materials['color_Palette.001']} position={[-0.763, 0.111, -0.722]} rotation={[0, -1.483, 0]} scale={0.053} />
      <mesh geometry={nodes.grass037.geometry} material={materials['color_Palette.001']} position={[-0.934, 0.107, 0.84]} rotation={[0.001, -1.146, 0.009]} scale={0.053} />
      <mesh geometry={nodes.grass038.geometry} material={materials['color_Palette.001']} position={[-0.832, 0.111, 0.921]} rotation={[0, -1.002, 0]} scale={0.053} />
      <mesh geometry={nodes.grass039.geometry} material={materials['color_Palette.001']} position={[-0.711, 0.111, 0.517]} rotation={[0, -1.002, 0]} scale={0.053} />
      <mesh geometry={nodes.grass040.geometry} material={materials['color_Palette.001']} position={[-0.711, 0.111, 0.627]} rotation={[0, 1.457, 0]} scale={0.053} />
      <mesh geometry={nodes.grass041.geometry} material={materials['color_Palette.001']} position={[-0.433, 0.111, 0.809]} rotation={[0, -1.39, 0]} scale={0.053} />
      <mesh geometry={nodes.grass042.geometry} material={materials['color_Palette.001']} position={[-0.562, 0.111, 0.807]} rotation={[0, -0.381, 0]} scale={0.053} />
      <mesh geometry={nodes.grass043.geometry} material={materials['color_Palette.001']} position={[-0.657, 0.111, 0.88]} rotation={[0, -1.46, 0]} scale={0.053} />
      <mesh geometry={nodes.grass044.geometry} material={materials['color_Palette.001']} position={[-1.014, 0.111, 0.696]} rotation={[0, -1.002, 0]} scale={0.053} />
      <mesh geometry={nodes.grass045.geometry} material={materials['color_Palette.001']} position={[0.834, 0.107, 0.94]} rotation={[0.001, 0.505, 0.008]} scale={0.053} />
      <mesh geometry={nodes.grass046.geometry} material={materials['color_Palette.001']} position={[0.906, 0.111, 0.832]} rotation={[0, 0.649, 0]} scale={0.053} />
      <mesh geometry={nodes.grass047.geometry} material={materials['color_Palette.001']} position={[0.493, 0.111, 0.743]} rotation={[0, 0.649, 0]} scale={0.053} />
      <mesh geometry={nodes.grass048.geometry} material={materials['color_Palette.001']} position={[0.603, 0.111, 0.735]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass049.geometry} material={materials['color_Palette.001']} position={[0.762, 0.111, 0.443]} rotation={[0, 0.262, 0]} scale={0.053} />
      <mesh geometry={nodes.grass050.geometry} material={materials['color_Palette.001']} position={[0.771, 0.111, 0.571]} rotation={[0, 1.27, 0]} scale={0.053} />
      <mesh geometry={nodes.grass051.geometry} material={materials['color_Palette.001']} position={[0.851, 0.111, 0.661]} rotation={[0, 0.192, 0]} scale={0.053} />
      <mesh geometry={nodes.grass052.geometry} material={materials['color_Palette.001']} position={[0.697, 0.111, 1.031]} rotation={[0, 0.649, 0]} scale={0.053} />
      <mesh geometry={nodes.grass053.geometry} material={materials['color_Palette.001']} position={[-1.131, 0.111, -1.452]} rotation={[Math.PI, -0.474, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass054.geometry} material={materials['color_Palette.001']} position={[-1.362, 0.111, -1.265]} rotation={[Math.PI, -0.474, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass055.geometry} material={materials['color_Palette.001']} position={[-1.852, 0.111, -0.166]} rotation={[Math.PI, -1.408, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass056.geometry} material={materials['color_Palette.001']} position={[-1.839, 0.111, 0.131]} rotation={[Math.PI, -1.408, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass057.geometry} material={materials['color_Palette.001']} position={[1.317, 0.111, 1.239]} rotation={[Math.PI, -0.53, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass058.geometry} material={materials['color_Palette.001']} position={[1.096, 0.111, 1.438]} rotation={[Math.PI, -0.53, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass059.geometry} material={materials['color_Palette.001']} position={[0.103, 0.111, 1.822]} rotation={[-Math.PI, 0.218, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass060.geometry} material={materials['color_Palette.001']} position={[-0.194, 0.111, 1.818]} rotation={[-Math.PI, 0.218, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass061.geometry} material={materials['color_Palette.001']} position={[-1.226, 0.111, 1.314]} rotation={[-Math.PI, 0.996, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass062.geometry} material={materials['color_Palette.001']} position={[-1.435, 0.111, 1.102]} rotation={[-Math.PI, 0.996, -Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass001.geometry} material={materials['color_Palette.001']} position={[0.171, 0.111, -1.766]} rotation={[0, 0.702, 0]} scale={0.053} />
      <mesh geometry={nodes.grass002.geometry} material={materials['color_Palette.001']} position={[-0.109, 0.111, -1.764]} rotation={[0, -0.662, 0]} scale={0.053} />
      <mesh geometry={nodes.grass003.geometry} material={materials['color_Palette.001']} position={[-0.036, 0.111, -1.638]} rotation={[0, -0.729, 0]} scale={0.053} />
      <mesh geometry={nodes.grass004.geometry} material={materials['color_Palette.001']} position={[1.756, 0.111, 0.104]} rotation={[0, -0.791, 0]} scale={0.053} />
      <mesh geometry={nodes.grass005.geometry} material={materials['color_Palette.001']} position={[1.732, 0.111, -0.175]} rotation={[Math.PI, -0.986, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.grass006.geometry} material={materials['color_Palette.001']} position={[1.612, 0.111, -0.092]} rotation={[Math.PI, -0.919, Math.PI]} scale={0.053} />
      <mesh geometry={nodes.flower4006.geometry} material={materials['color_Palette.002']} position={[0.665, 0.107, -0.739]} rotation={[0.025, 1.26, -0.022]} scale={0.031} />
      <mesh geometry={nodes.flower4016.geometry} material={materials['color_Palette.002']} position={[1.422, 0.107, -1.201]} rotation={[0, 0.924, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4017.geometry} material={materials['color_Palette.002']} position={[1.213, 0.107, -1.413]} rotation={[0, 0.924, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4018.geometry} material={materials['color_Palette.002']} position={[0.711, 0.107, -0.452]} rotation={[0, 0.924, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4019.geometry} material={materials['color_Palette.002']} position={[0.721, 0.107, -0.545]} rotation={[Math.PI, -0.242, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4020.geometry} material={materials['color_Palette.002']} position={[0.814, 0.107, -0.473]} rotation={[-Math.PI, 0.949, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4021.geometry} material={materials['color_Palette.002']} position={[0.436, 0.107, -0.745]} rotation={[0, 0.537, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4022.geometry} material={materials['color_Palette.002']} position={[0.559, 0.107, -0.737]} rotation={[0, 1.545, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4023.geometry} material={materials['color_Palette.002']} position={[0.66, 0.107, -0.818]} rotation={[0, 0.467, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4024.geometry} material={materials['color_Palette.002']} position={[0.743, 0.107, -0.694]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4025.geometry} material={materials['color_Palette.002']} position={[0.548, 0.107, -0.976]} rotation={[3.12, 1.207, -3.119]} scale={0.031} />
      <mesh geometry={nodes.flower4026.geometry} material={materials['color_Palette.002']} position={[1.036, 0.107, -0.633]} rotation={[0, 0.924, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4027.geometry} material={materials['color_Palette.002']} position={[-0.925, 0.107, -0.798]} rotation={[-Math.PI, 0.628, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4028.geometry} material={materials['color_Palette.002']} position={[-0.518, 0.107, -0.686]} rotation={[-Math.PI, 0.628, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4029.geometry} material={materials['color_Palette.002']} position={[-0.611, 0.107, -0.693]} rotation={[0, -1.31, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4030.geometry} material={materials['color_Palette.002']} position={[-0.54, 0.107, -0.788]} rotation={[Math.PI, -0.64, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4031.geometry} material={materials['color_Palette.002']} position={[-0.806, 0.107, -0.405]} rotation={[-Math.PI, 1.016, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4032.geometry} material={materials['color_Palette.002']} position={[-0.8, 0.107, -0.528]} rotation={[-Math.PI, 0.007, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4033.geometry} material={materials['color_Palette.002']} position={[-0.883, 0.107, -0.628]} rotation={[-Math.PI, 1.086, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4034.geometry} material={materials['color_Palette.002']} position={[-1.039, 0.107, -0.513]} rotation={[3.133, -0.382, 3.141]} scale={0.031} />
      <mesh geometry={nodes.flower4036.geometry} material={materials['color_Palette.002']} position={[-0.928, 0.104, 0.848]} rotation={[3.131, -0.776, 3.136]} scale={0.031} />
      <mesh geometry={nodes.flower4037.geometry} material={materials['color_Palette.002']} position={[-0.824, 0.107, 0.928]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4038.geometry} material={materials['color_Palette.002']} position={[-0.703, 0.107, 0.524]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4039.geometry} material={materials['color_Palette.002']} position={[-0.713, 0.107, 0.617]} rotation={[0, 0.238, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4040.geometry} material={materials['color_Palette.002']} position={[-0.806, 0.107, 0.543]} rotation={[0, -0.953, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4041.geometry} material={materials['color_Palette.002']} position={[-0.429, 0.107, 0.818]} rotation={[Math.PI, -0.533, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4042.geometry} material={materials['color_Palette.002']} position={[-0.552, 0.107, 0.809]} rotation={[Math.PI, -1.541, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4043.geometry} material={materials['color_Palette.002']} position={[-0.653, 0.107, 0.889]} rotation={[Math.PI, -0.463, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4044.geometry} material={materials['color_Palette.002']} position={[-0.542, 0.107, 1.048]} rotation={[0.022, -1.211, 0.023]} scale={0.031} />
      <mesh geometry={nodes.flower4045.geometry} material={materials['color_Palette.002']} position={[-1.007, 0.107, 0.703]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4046.geometry} material={materials['color_Palette.002']} position={[0.841, 0.104, 0.933]} rotation={[0.01, -0.714, 0.009]} scale={0.031} />
      <mesh geometry={nodes.flower4047.geometry} material={materials['color_Palette.002']} position={[0.912, 0.107, 0.824]} rotation={[0, -0.57, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4048.geometry} material={materials['color_Palette.002']} position={[0.5, 0.107, 0.735]} rotation={[0, -0.57, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4049.geometry} material={materials['color_Palette.002']} position={[0.593, 0.107, 0.737]} rotation={[-Math.PI, 1.252, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4050.geometry} material={materials['color_Palette.002']} position={[0.528, 0.107, 0.836]} rotation={[0, 0.698, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4051.geometry} material={materials['color_Palette.002']} position={[0.771, 0.107, 0.438]} rotation={[0, -0.957, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4052.geometry} material={materials['color_Palette.002']} position={[0.772, 0.107, 0.561]} rotation={[0, 0.051, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4053.geometry} material={materials['color_Palette.002']} position={[0.86, 0.107, 0.656]} rotation={[0, -1.028, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4054.geometry} material={materials['color_Palette.002']} position={[1.009, 0.107, 0.532]} rotation={[0.009, 0.44, -0.001]} scale={0.031} />
      <mesh geometry={nodes.flower4055.geometry} material={materials['color_Palette.002']} position={[0.703, 0.107, 1.023]} rotation={[0, -0.57, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4056.geometry} material={materials['color_Palette.002']} position={[-1.138, 0.107, -1.445]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4057.geometry} material={materials['color_Palette.002']} position={[-1.37, 0.107, -1.258]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4058.geometry} material={materials['color_Palette.002']} position={[-1.851, 0.107, -0.156]} rotation={[Math.PI, -0.189, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4059.geometry} material={materials['color_Palette.002']} position={[-1.838, 0.107, 0.141]} rotation={[Math.PI, -0.189, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4060.geometry} material={materials['color_Palette.002']} position={[1.309, 0.107, 1.246]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4061.geometry} material={materials['color_Palette.002']} position={[0.093, 0.107, 1.822]} rotation={[-Math.PI, 1.437, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4062.geometry} material={materials['color_Palette.002']} position={[-1.233, 0.107, 1.307]} rotation={[0, 0.926, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4001.geometry} material={materials['color_Palette.002']} position={[0.177, 0.107, -1.774]} rotation={[0, -0.517, 0]} scale={0.031} />
      <mesh geometry={nodes.flower4002.geometry} material={materials['color_Palette.002']} position={[-0.1, 0.107, -1.76]} rotation={[Math.PI, -1.26, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4003.geometry} material={materials['color_Palette.002']} position={[-0.027, 0.107, -1.633]} rotation={[Math.PI, -1.193, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4004.geometry} material={materials['color_Palette.002']} position={[1.765, 0.107, 0.109]} rotation={[Math.PI, -1.131, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4005.geometry} material={materials['color_Palette.002']} position={[1.729, 0.107, -0.166]} rotation={[-Math.PI, 0.233, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower4007.geometry} material={materials['color_Palette.002']} position={[1.608, 0.107, -0.083]} rotation={[-Math.PI, 0.3, -Math.PI]} scale={0.031} />
      <mesh geometry={nodes.flower3006.geometry} material={materials['color_Palette.002']} position={[0.685, 0.109, -0.728]} rotation={[0.025, 1.26, -0.022]} scale={0.035} />
      <mesh geometry={nodes.flower3016.geometry} material={materials['color_Palette.002']} position={[1.438, 0.11, -1.184]} rotation={[0, 0.924, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3017.geometry} material={materials['color_Palette.002']} position={[1.229, 0.11, -1.396]} rotation={[0, 0.924, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3018.geometry} material={materials['color_Palette.002']} position={[0.728, 0.11, -0.436]} rotation={[0, 0.924, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3019.geometry} material={materials['color_Palette.002']} position={[0.718, 0.11, -0.568]} rotation={[Math.PI, -0.242, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3020.geometry} material={materials['color_Palette.002']} position={[0.835, 0.11, -0.483]} rotation={[-Math.PI, 0.949, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3021.geometry} material={materials['color_Palette.002']} position={[0.445, 0.11, -0.724]} rotation={[0, 0.537, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3022.geometry} material={materials['color_Palette.002']} position={[0.582, 0.11, -0.733]} rotation={[0, 1.545, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3023.geometry} material={materials['color_Palette.002']} position={[0.667, 0.11, -0.796]} rotation={[0, 0.467, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3024.geometry} material={materials['color_Palette.002']} position={[0.765, 0.11, -0.7]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3030.geometry} material={materials['color_Palette.002']} position={[0.57, 0.109, -0.981]} rotation={[3.12, 1.207, -3.119]} scale={0.035} />
      <mesh geometry={nodes.flower3032.geometry} material={materials['color_Palette.002']} position={[1.052, 0.11, -0.616]} rotation={[0, 0.924, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3033.geometry} material={materials['color_Palette.002']} position={[-0.909, 0.11, -0.815]} rotation={[-Math.PI, 0.628, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3034.geometry} material={materials['color_Palette.002']} position={[-0.794, 0.109, -0.655]} rotation={[3.133, 0.293, -3.137]} scale={0.035} />
      <mesh geometry={nodes.flower3035.geometry} material={materials['color_Palette.002']} position={[-0.502, 0.11, -0.702]} rotation={[-Math.PI, 0.628, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3036.geometry} material={materials['color_Palette.002']} position={[-0.634, 0.11, -0.691]} rotation={[0, -1.31, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3037.geometry} material={materials['color_Palette.002']} position={[-0.551, 0.11, -0.809]} rotation={[Math.PI, -0.64, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3038.geometry} material={materials['color_Palette.002']} position={[-0.785, 0.11, -0.414]} rotation={[-Math.PI, 1.016, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3039.geometry} material={materials['color_Palette.002']} position={[-0.796, 0.11, -0.551]} rotation={[-Math.PI, 0.007, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3040.geometry} material={materials['color_Palette.002']} position={[-0.861, 0.11, -0.636]} rotation={[-Math.PI, 1.086, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3041.geometry} material={materials['color_Palette.002']} position={[-0.766, 0.11, -0.735]} rotation={[Math.PI, -0.439, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3047.geometry} material={materials['color_Palette.002']} position={[-1.044, 0.109, -0.535]} rotation={[3.133, -0.382, 3.141]} scale={0.035} />
      <mesh geometry={nodes.flower3050.geometry} material={materials['color_Palette.002']} position={[-0.941, 0.106, 0.829]} rotation={[3.131, -0.776, 3.136]} scale={0.035} />
      <mesh geometry={nodes.flower3051.geometry} material={materials['color_Palette.002']} position={[-0.841, 0.11, 0.911]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3052.geometry} material={materials['color_Palette.002']} position={[-0.678, 0.109, 0.8]} rotation={[3.116, -1.255, 3.12]} scale={0.035} />
      <mesh geometry={nodes.flower3053.geometry} material={materials['color_Palette.002']} position={[-0.719, 0.11, 0.507]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3054.geometry} material={materials['color_Palette.002']} position={[-0.711, 0.11, 0.64]} rotation={[0, 0.238, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3055.geometry} material={materials['color_Palette.002']} position={[-0.827, 0.11, 0.554]} rotation={[0, -0.953, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3056.geometry} material={materials['color_Palette.002']} position={[-0.437, 0.11, 0.796]} rotation={[Math.PI, -0.533, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3057.geometry} material={materials['color_Palette.002']} position={[-0.574, 0.11, 0.804]} rotation={[Math.PI, -1.541, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3058.geometry} material={materials['color_Palette.002']} position={[-0.66, 0.11, 0.867]} rotation={[Math.PI, -0.463, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3064.geometry} material={materials['color_Palette.002']} position={[-0.564, 0.109, 1.052]} rotation={[0.022, -1.211, 0.023]} scale={0.035} />
      <mesh geometry={nodes.flower3066.geometry} material={materials['color_Palette.002']} position={[-1.023, 0.11, 0.687]} rotation={[Math.PI, -0.92, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3067.geometry} material={materials['color_Palette.002']} position={[0.824, 0.106, 0.948]} rotation={[0.01, -0.714, 0.009]} scale={0.035} />
      <mesh geometry={nodes.flower3068.geometry} material={materials['color_Palette.002']} position={[0.897, 0.11, 0.841]} rotation={[0, -0.57, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3069.geometry} material={materials['color_Palette.002']} position={[0.773, 0.109, 0.688]} rotation={[0.008, -0.235, 0.004]} scale={0.035} />
      <mesh geometry={nodes.flower3070.geometry} material={materials['color_Palette.002']} position={[0.484, 0.11, 0.753]} rotation={[0, -0.57, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3071.geometry} material={materials['color_Palette.002']} position={[0.616, 0.11, 0.733]} rotation={[-Math.PI, 1.252, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3072.geometry} material={materials['color_Palette.002']} position={[0.54, 0.11, 0.856]} rotation={[0, 0.698, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3073.geometry} material={materials['color_Palette.002']} position={[0.75, 0.11, 0.448]} rotation={[0, -0.957, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3074.geometry} material={materials['color_Palette.002']} position={[0.769, 0.11, 0.584]} rotation={[0, 0.051, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3075.geometry} material={materials['color_Palette.002']} position={[0.839, 0.11, 0.665]} rotation={[0, -1.028, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3081.geometry} material={materials['color_Palette.002']} position={[1.016, 0.109, 0.554]} rotation={[0.009, 0.44, -0.001]} scale={0.035} />
      <mesh geometry={nodes.flower3083.geometry} material={materials['color_Palette.002']} position={[0.688, 0.11, 1.041]} rotation={[0, -0.57, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3084.geometry} material={materials['color_Palette.002']} position={[-1.12, 0.11, -1.46]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3085.geometry} material={materials['color_Palette.002']} position={[-1.352, 0.11, -1.273]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3086.geometry} material={materials['color_Palette.002']} position={[-1.851, 0.11, -0.179]} rotation={[Math.PI, -0.189, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3087.geometry} material={materials['color_Palette.002']} position={[-1.839, 0.11, 0.118]} rotation={[Math.PI, -0.189, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3088.geometry} material={materials['color_Palette.002']} position={[1.327, 0.11, 1.231]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3089.geometry} material={materials['color_Palette.002']} position={[1.106, 0.11, 1.43]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3090.geometry} material={materials['color_Palette.002']} position={[0.116, 0.11, 1.823]} rotation={[-Math.PI, 1.437, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3091.geometry} material={materials['color_Palette.002']} position={[-0.181, 0.11, 1.819]} rotation={[-Math.PI, 1.437, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3092.geometry} material={materials['color_Palette.002']} position={[-1.217, 0.11, 1.324]} rotation={[0, 0.926, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3093.geometry} material={materials['color_Palette.002']} position={[-1.426, 0.11, 1.112]} rotation={[0, 0.926, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3001.geometry} material={materials['color_Palette.002']} position={[0.163, 0.11, -1.756]} rotation={[0, -0.517, 0]} scale={0.035} />
      <mesh geometry={nodes.flower3002.geometry} material={materials['color_Palette.002']} position={[-0.121, 0.11, -1.77]} rotation={[Math.PI, -1.26, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3003.geometry} material={materials['color_Palette.002']} position={[-0.047, 0.11, -1.645]} rotation={[Math.PI, -1.193, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3004.geometry} material={materials['color_Palette.002']} position={[1.746, 0.11, 0.096]} rotation={[Math.PI, -1.131, Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3005.geometry} material={materials['color_Palette.002']} position={[1.738, 0.11, -0.187]} rotation={[-Math.PI, 0.233, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.flower3007.geometry} material={materials['color_Palette.002']} position={[1.618, 0.11, -0.104]} rotation={[-Math.PI, 0.3, -Math.PI]} scale={0.035} />
      <mesh geometry={nodes.mushroom.geometry} material={materials['color_Palette.003']} position={[1.418, 0.107, -1.17]} rotation={[0, 0.705, 0]} scale={0.087} />
      <mesh geometry={nodes.mushroom001.geometry} material={materials['color_Palette.003']} position={[1.195, 0.107, -1.392]} rotation={[0, 0.169, 0]} scale={0.087} />
      <mesh geometry={nodes.mushroom002.geometry} material={materials['color_Palette.003']} position={[-1.108, 0.107, -1.438]} rotation={[-Math.PI, 0.964, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom003.geometry} material={materials['color_Palette.003']} position={[-1.352, 0.107, -1.239]} rotation={[-Math.PI, 1.5, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom004.geometry} material={materials['color_Palette.003']} position={[-1.827, 0.107, -0.176]} rotation={[-Math.PI, 0.03, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom005.geometry} material={materials['color_Palette.003']} position={[-1.812, 0.107, 0.138]} rotation={[-Math.PI, 0.566, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom006.geometry} material={materials['color_Palette.003']} position={[1.34, 0.107, 1.251]} rotation={[-Math.PI, 0.909, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom007.geometry} material={materials['color_Palette.003']} position={[1.108, 0.107, 1.464]} rotation={[-Math.PI, 1.445, -Math.PI]} scale={0.087} />
      <mesh geometry={nodes.mushroom008.geometry} material={materials['color_Palette.003']} position={[0.112, 0.107, 1.847]} rotation={[0, 1.485, 0]} scale={0.087} />
      <mesh geometry={nodes.mushroom009.geometry} material={materials['color_Palette.003']} position={[-0.202, 0.107, 1.845]} rotation={[0, 0.949, 0]} scale={0.087} />
      <mesh geometry={nodes.mushroom010.geometry} material={materials['color_Palette.003']} position={[-1.237, 0.107, 1.338]} rotation={[0, 0.707, 0]} scale={0.087} />
      <mesh geometry={nodes.mushroom011.geometry} material={materials['color_Palette.003']} position={[-1.46, 0.107, 1.116]} rotation={[0, 0.171, 0]} scale={0.087} />
      <mesh geometry={nodes.mini_rock_5.geometry} material={materials['color_Palette.004']} position={[0.775, 0.104, -0.4]} rotation={[0, 0.777, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5001.geometry} material={materials['color_Palette.004']} position={[0.627, 0.104, -0.606]} rotation={[Math.PI, -1.17, Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5004.geometry} material={materials['color_Palette.004']} position={[-0.467, 0.104, -0.751]} rotation={[-Math.PI, 0.776, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5005.geometry} material={materials['color_Palette.004']} position={[-0.885, 0.104, -0.548]} rotation={[0, 1.167, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5008.geometry} material={materials['color_Palette.004']} position={[-0.767, 0.104, 0.471]} rotation={[Math.PI, -0.772, Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5009.geometry} material={materials['color_Palette.004']} position={[-0.619, 0.104, 0.677]} rotation={[0, 1.166, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5012.geometry} material={materials['color_Palette.004']} position={[0.453, 0.104, 0.803]} rotation={[0, -0.718, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5013.geometry} material={materials['color_Palette.004']} position={[0.646, 0.104, 0.639]} rotation={[-Math.PI, 0.324, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5002.geometry} material={materials['color_Palette.004']} position={[-0.988, 0.104, 0.51]} rotation={[0, -0.023, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5003.geometry} material={materials['color_Palette.004']} position={[-0.403, 0.104, 1.144]} rotation={[Math.PI, -1.357, Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5006.geometry} material={materials['color_Palette.004']} position={[0.478, 0.104, 0.951]} rotation={[0, -0.049, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5007.geometry} material={materials['color_Palette.004']} position={[0.998, 0.104, 0.368]} rotation={[0, -1.424, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5010.geometry} material={materials['color_Palette.004']} position={[0.971, 0.104, -0.472]} rotation={[0, 1.213, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5011.geometry} material={materials['color_Palette.004']} position={[0.456, 0.104, -1.084]} rotation={[0, 0.276, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5014.geometry} material={materials['color_Palette.004']} position={[-0.493, 0.104, -0.922]} rotation={[0, 1.414, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5015.geometry} material={materials['color_Palette.004']} position={[0.065, 0.104, -1.754]} rotation={[0, 1.209, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5016.geometry} material={materials['color_Palette.004']} position={[1.736, 0.104, -0.001]} rotation={[0, -0.284, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5017.geometry} material={materials['color_Palette.004']} position={[0.697, 0.045, 1.872]} rotation={[Math.PI, -1.125, Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5018.geometry} material={materials['color_Palette.004']} position={[-1, 0.048, 1.68]} rotation={[0, -1.377, 0]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5019.geometry} material={materials['color_Palette.004']} position={[-1.614, 0.074, 1.132]} rotation={[Math.PI, -0.406, Math.PI]} scale={0.099} />
      <mesh geometry={nodes.mini_rock_5020.geometry} material={materials['color_Palette.004']} position={[-1.642, 0.06, -1.089]} rotation={[-Math.PI, 0.106, -Math.PI]} scale={0.099} />
      <mesh geometry={nodes.flower3025.geometry} material={materials['color_Palette.006']} position={[0.887, 0.11, -0.719]} scale={0.036} />
      <mesh geometry={nodes.flower3026.geometry} material={materials['color_Palette.006']} position={[0.955, 0.11, -0.64]} rotation={[0, 1.287, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3027.geometry} material={materials['color_Palette.006']} position={[0.661, 0.109, -0.941]} rotation={[0, 0.626, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3028.geometry} material={materials['color_Palette.006']} position={[0.794, 0.107, -0.941]} rotation={[0, 0.626, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3029.geometry} material={materials['color_Palette.006']} position={[0.866, 0.107, -0.805]} rotation={[0, -1.11, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3031.geometry} material={materials['color_Palette.006']} position={[0.94, 0.11, -0.526]} rotation={[0, -0.078, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3042.geometry} material={materials['color_Palette.006']} position={[-0.788, 0.11, -0.857]} rotation={[-Math.PI, 1.552, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3043.geometry} material={materials['color_Palette.006']} position={[-0.711, 0.11, -0.926]} rotation={[-Math.PI, 0.265, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3044.geometry} material={materials['color_Palette.006']} position={[-1.005, 0.109, -0.627]} rotation={[-Math.PI, 0.926, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3045.geometry} material={materials['color_Palette.006']} position={[-1.008, 0.107, -0.679]} rotation={[-Math.PI, 0.926, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3046.geometry} material={materials['color_Palette.006']} position={[-0.874, 0.107, -0.834]} rotation={[0, 0.479, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3048.geometry} material={materials['color_Palette.006']} position={[-0.597, 0.11, -0.913]} rotation={[0, 1.511, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3059.geometry} material={materials['color_Palette.006']} position={[-0.88, 0.11, 0.79]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3060.geometry} material={materials['color_Palette.006']} position={[-0.947, 0.11, 0.71]} rotation={[Math.PI, -1.283, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3061.geometry} material={materials['color_Palette.006']} position={[-0.655, 0.109, 1.012]} rotation={[Math.PI, -0.622, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3062.geometry} material={materials['color_Palette.006']} position={[-0.707, 0.107, 1.013]} rotation={[Math.PI, -0.622, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3063.geometry} material={materials['color_Palette.006']} position={[-0.859, 0.107, 0.876]} rotation={[-Math.PI, 1.115, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3065.geometry} material={materials['color_Palette.006']} position={[-0.932, 0.11, 0.597]} rotation={[-Math.PI, 0.082, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3076.geometry} material={materials['color_Palette.006']} position={[0.779, 0.11, 0.89]} rotation={[0, -1.494, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3077.geometry} material={materials['color_Palette.006']} position={[0.706, 0.11, 0.963]} rotation={[0, -0.207, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3078.geometry} material={materials['color_Palette.006']} position={[0.983, 0.109, 0.648]} rotation={[0, -0.868, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3079.geometry} material={materials['color_Palette.006']} position={[0.988, 0.107, 0.699]} rotation={[0, -0.868, 0]} scale={0.036} />
      <mesh geometry={nodes.flower3080.geometry} material={materials['color_Palette.006']} position={[0.863, 0.107, 0.862]} rotation={[Math.PI, -0.537, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower3082.geometry} material={materials['color_Palette.006']} position={[0.591, 0.11, 0.957]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2.geometry} material={materials['color_Palette.006']} position={[0.887, 0.116, -0.699]} scale={0.036} />
      <mesh geometry={nodes.flower2001.geometry} material={materials['color_Palette.006']} position={[0.974, 0.116, -0.635]} rotation={[0, 1.287, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2002.geometry} material={materials['color_Palette.006']} position={[0.673, 0.115, -0.924]} rotation={[0, 0.626, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2003.geometry} material={materials['color_Palette.006']} position={[0.806, 0.113, -0.924]} rotation={[0, 0.626, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2004.geometry} material={materials['color_Palette.006']} position={[0.847, 0.113, -0.796]} rotation={[0, -1.11, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2005.geometry} material={materials['color_Palette.006']} position={[0.938, 0.116, -0.506]} rotation={[0, -0.078, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2006.geometry} material={materials['color_Palette.006']} position={[-0.768, 0.116, -0.857]} rotation={[-Math.PI, 1.552, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2007.geometry} material={materials['color_Palette.006']} position={[-0.705, 0.116, -0.946]} rotation={[-Math.PI, 0.265, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2008.geometry} material={materials['color_Palette.006']} position={[-0.989, 0.115, -0.639]} rotation={[-Math.PI, 0.926, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2009.geometry} material={materials['color_Palette.006']} position={[-0.992, 0.113, -0.691]} rotation={[-Math.PI, 0.926, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2010.geometry} material={materials['color_Palette.006']} position={[-0.864, 0.113, -0.816]} rotation={[0, 0.479, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2011.geometry} material={materials['color_Palette.006']} position={[-0.576, 0.116, -0.912]} rotation={[0, 1.511, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2012.geometry} material={materials['color_Palette.006']} position={[-0.88, 0.116, 0.769]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2013.geometry} material={materials['color_Palette.006']} position={[-0.967, 0.116, 0.705]} rotation={[Math.PI, -1.283, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2014.geometry} material={materials['color_Palette.006']} position={[-0.667, 0.115, 0.995]} rotation={[Math.PI, -0.622, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2015.geometry} material={materials['color_Palette.006']} position={[-0.719, 0.113, 0.997]} rotation={[Math.PI, -0.622, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2016.geometry} material={materials['color_Palette.006']} position={[-0.84, 0.113, 0.866]} rotation={[-Math.PI, 1.115, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2017.geometry} material={materials['color_Palette.006']} position={[-0.93, 0.116, 0.576]} rotation={[-Math.PI, 0.082, -Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2018.geometry} material={materials['color_Palette.006']} position={[0.759, 0.116, 0.892]} rotation={[0, -1.494, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2019.geometry} material={materials['color_Palette.006']} position={[0.702, 0.116, 0.983]} rotation={[0, -0.207, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2020.geometry} material={materials['color_Palette.006']} position={[0.967, 0.115, 0.661]} rotation={[0, -0.868, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2021.geometry} material={materials['color_Palette.006']} position={[0.973, 0.113, 0.713]} rotation={[0, -0.868, 0]} scale={0.036} />
      <mesh geometry={nodes.flower2022.geometry} material={materials['color_Palette.006']} position={[0.853, 0.113, 0.845]} rotation={[Math.PI, -0.537, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.flower2023.geometry} material={materials['color_Palette.006']} position={[0.571, 0.116, 0.957]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.036} />
      <mesh geometry={nodes.plant3.geometry} material={materials['color_Palette.007']} position={[0.599, 0.133, 0.2]} scale={0.094} />
      <mesh geometry={nodes.plant3001.geometry} material={materials['color_Palette.007']} position={[0.574, 0.133, -0.255]} rotation={[0, 1.155, 0]} scale={0.094} />
      <mesh geometry={nodes.plant3002.geometry} material={materials['color_Palette.007']} position={[-0.1, 0.133, -0.611]} rotation={[0, -0.573, 0]} scale={0.094} />
      <mesh geometry={nodes.plant3003.geometry} material={materials['color_Palette.007']} position={[-0.608, 0.133, -0.255]} rotation={[Math.PI, -1.25, Math.PI]} scale={0.094} />
      <mesh geometry={nodes.plant3004.geometry} material={materials['color_Palette.007']} position={[-0.516, 0.128, 0.404]} rotation={[-Math.PI, 0.117, -Math.PI]} scale={0.094} />
      <mesh geometry={nodes.plant3005.geometry} material={materials['color_Palette.007']} position={[0.018, 0.128, 0.689]} rotation={[-Math.PI, 1.477, -Math.PI]} scale={0.094} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.006']} position={[0.318, 0.629, -0.316]} rotation={[1.563, 0.001, -2.363]} scale={0.125} />
      <group position={[-0.051, 0.223, -0.958]} rotation={[0, -1.566, 0]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[0.709, 0.217, -1.54]} rotation={[0, 1.265, 0]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[0.965, 0.223, -0.033]} rotation={[Math.PI, -0.027, Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[0.03, 0.217, 0.954]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-0.974, 0.223, 0.025]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[1.6, 0.224, -0.56]} rotation={[0, 0.402, 0]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[1.545, 0.221, 0.69]} rotation={[0, -0.288, 0]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[0.549, 0.218, 1.597]} rotation={[0, -1.245, 0]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-0.626, 0.218, 1.552]} rotation={[Math.PI, -1.18, Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-1.561, 0.221, 0.559]} rotation={[Math.PI, -0.359, Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-1.542, 0.238, -0.627]} rotation={[-Math.PI, 0.402, -Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-0.551, 0.211, -1.569]} rotation={[-Math.PI, 1.205, -Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['negro_soporte.001']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.negro_soporte} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['color_Palette.009']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.023']} position={[-2.068, 0.292, -1.854]} rotation={[0, -0.888, 0]} scale={0.006} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.023']} position={[-2.013, 0.292, -1.899]} rotation={[0, -0.888, 0]} scale={0.006} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.023']} position={[-1.576, 0.292, -2.255]} rotation={[0, -0.888, 0]} scale={0.006} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['Material.023']} position={[-1.635, 0.292, -2.207]} rotation={[0, -0.888, 0]} scale={0.006} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.023']} position={[-1.791, 0.357, -2.262]} rotation={[0, -0.888, 0]} scale={0.006} />
      <mesh geometry={nodes.Plane022.geometry} material={materials['Material.024']} position={[-1.787, 0.69, -2.748]} rotation={[0, -0.888, -Math.PI / 2]} scale={[0.078, 0.078, 0.05]} />
      <mesh geometry={nodes.flower1005.geometry} material={materials['color_Palette.011']} position={[-2.068, 0.304, -1.853]} rotation={[Math.PI, -0.967, Math.PI]} scale={0.028} />
      <mesh geometry={nodes.flower1026.geometry} material={materials['color_Palette.011']} position={[-2.013, 0.304, -1.898]} rotation={[Math.PI, -0.967, Math.PI]} scale={0.028} />
      <mesh geometry={nodes.flower1027.geometry} material={materials['color_Palette.011']} position={[-1.576, 0.304, -2.254]} rotation={[Math.PI, -0.967, Math.PI]} scale={0.028} />
      <mesh geometry={nodes.flower1028.geometry} material={materials['color_Palette.011']} position={[-1.635, 0.304, -2.206]} rotation={[Math.PI, -0.967, Math.PI]} scale={0.028} />
      <mesh geometry={nodes.flower1.geometry} material={materials['color_Palette.011']} position={[-1.79, 0.369, -2.261]} rotation={[Math.PI, -0.967, Math.PI]} scale={0.028} />
      <group position={[-1.789, 0.314, -2.258]} rotation={[0, -0.888, 0]} scale={0.034}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.026']} />
      </group>
      <group position={[-2.004, 0.314, -2.084]} rotation={[0, -0.888, 0]} scale={0.034}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.026']} />
      </group>
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-2.007, 0.279, -2.298]} rotation={[0, -0.888, 0]} scale={[0.488, 0.002, 0.488]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} position={[-3.004, 0.279, 0.002]} rotation={[0, -0.888, 0]} scale={[0.488, 0.002, 0.488]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[-2.192, 0.279, 2.05]} rotation={[0, -0.188, 0]} scale={[0.488, 0.002, 0.488]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} position={[-0.018, 0.279, 3.03]} rotation={[0, 0.668, 0]} scale={[0.488, 0.002, 0.488]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[2.088, 0.279, 2.202]} rotation={[0, 1.455, 0]} scale={[0.488, 0.002, 0.488]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials['Material.027']} position={[-1.79, 0.352, -2.261]} rotation={[0, -0.888, 0]} scale={-0.008} />
      <mesh geometry={nodes.Cube215.geometry} material={materials['Material.027']} position={[-2.068, 0.287, -1.854]} rotation={[0, -0.888, 0]} scale={-0.008} />
      <mesh geometry={nodes.Cube216.geometry} material={materials['Material.027']} position={[-2.013, 0.287, -1.898]} rotation={[0, -0.888, 0]} scale={-0.008} />
      <mesh geometry={nodes.Cube217.geometry} material={materials['Material.027']} position={[-1.576, 0.287, -2.254]} rotation={[0, -0.888, 0]} scale={-0.008} />
      <mesh geometry={nodes.Cube218.geometry} material={materials['Material.027']} position={[-1.635, 0.287, -2.206]} rotation={[0, -0.888, 0]} scale={-0.008} />
      <mesh geometry={nodes.Cube214.geometry} material={materials['negro_soporte.003']} position={[-1.83, 0.291, -2.714]} rotation={[0, -0.888, 0]} scale={0.006} />
      <group position={[-1.654, 0.374, -2.289]} rotation={[0, -0.888, 0]} scale={[0.069, 0.095, 0.048]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.028']} />
      </group>
      <group position={[-2.089, 0.374, -1.936]} rotation={[0, -0.888, 0]} scale={[0.069, 0.095, 0.048]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.028']} />
      </group>
      <mesh geometry={nodes.Cube221.geometry} material={materials['Material.028']} position={[-2.147, 0.402, -2.464]} rotation={[-Math.PI, 0.888, 0]} scale={[-0.009, -0.122, -0.172]} />
      <group position={[-2.135, 0.384, -2.45]} rotation={[0, -0.888, 0]} scale={[0.019, 0.107, 0.307]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Material.025']} />
      </group>
      <mesh geometry={nodes.Plane023.geometry} material={materials['Material.031']} position={[-3.186, 0.353, -0.118]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['Material.031']} position={[-3.178, 0.353, 0.103]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Plane025.geometry} material={materials['Material.032']} position={[-3.21, 0.636, -0.26]} rotation={[0, 0.026, -Math.PI / 2]} scale={[0.069, 0.069, 0.045]} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['Material.032']} position={[-2.519, 0.636, 1.983]} rotation={[0, 0.726, -Math.PI / 2]} scale={[0.069, 0.069, 0.045]} />
      <mesh geometry={nodes.Plane027.geometry} material={materials['Material.032']} position={[-0.283, 0.636, 3.233]} rotation={[-Math.PI, 1.56, Math.PI / 2]} scale={[0.069, 0.069, 0.045]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials['Material.032']} position={[2.045, 0.636, 2.533]} rotation={[-Math.PI, 0.773, Math.PI / 2]} scale={[0.069, 0.069, 0.045]} />
      <mesh geometry={nodes.flower1029.geometry} material={materials['color_Palette.012']} position={[-3.185, 0.364, -0.118]} rotation={[0, 0.316, 0]} scale={0.026} />
      <mesh geometry={nodes.flower1030.geometry} material={materials['color_Palette.012']} position={[-3.178, 0.364, 0.103]} rotation={[0, 0.316, 0]} scale={0.026} />
      <mesh geometry={nodes.flower1031.geometry} material={materials['color_Palette.012']} position={[-2.408, 0.364, 2.075]} rotation={[0, 1.016, 0]} scale={0.026} />
      <mesh geometry={nodes.flower1032.geometry} material={materials['color_Palette.012']} position={[-2.261, 0.364, 2.239]} rotation={[0, 1.016, 0]} scale={0.026} />
      <mesh geometry={nodes.flower1033.geometry} material={materials['color_Palette.012']} position={[-0.141, 0.364, 3.21]} rotation={[-Math.PI, 1.27, -Math.PI]} scale={0.026} />
      <mesh geometry={nodes.flower1034.geometry} material={materials['color_Palette.012']} position={[0.08, 0.364, 3.206]} rotation={[-Math.PI, 1.27, -Math.PI]} scale={0.026} />
      <mesh geometry={nodes.flower1035.geometry} material={materials['color_Palette.012']} position={[2.129, 0.364, 2.416]} rotation={[-Math.PI, 0.483, -Math.PI]} scale={0.026} />
      <mesh geometry={nodes.flower1036.geometry} material={materials['color_Palette.012']} position={[2.282, 0.364, 2.257]} rotation={[-Math.PI, 0.483, -Math.PI]} scale={0.026} />
      <mesh geometry={nodes.Cube223.geometry} material={materials['Material.033']} position={[-3.185, 0.348, -0.118]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube224.geometry} material={materials['Material.033']} position={[-3.178, 0.348, 0.103]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube225.geometry} material={materials['Material.033']} position={[-2.408, 0.348, 2.075]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube240.geometry} material={materials['Material.033']} position={[-2.26, 0.348, 2.239]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube255.geometry} material={materials['Material.033']} position={[-0.141, 0.348, 3.21]} rotation={[Math.PI, -0.017, Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube256.geometry} material={materials['Material.033']} position={[0.08, 0.348, 3.206]} rotation={[Math.PI, -0.017, Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube271.geometry} material={materials['Material.033']} position={[2.129, 0.348, 2.416]} rotation={[Math.PI, -0.804, Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube272.geometry} material={materials['Material.033']} position={[2.282, 0.348, 2.257]} rotation={[Math.PI, -0.804, Math.PI]} scale={-0.007} />
      <mesh geometry={nodes.Cube226.geometry} material={materials['negro_soporte.004']} position={[-3.21, 0.284, -0.212]} rotation={[0, 0.026, 0]} scale={0.006} />
      <mesh geometry={nodes.Cube241.geometry} material={materials['negro_soporte.004']} position={[-2.487, 0.284, 2.019]} rotation={[0, 0.726, 0]} scale={0.006} />
      <mesh geometry={nodes.Cube257.geometry} material={materials['negro_soporte.004']} position={[-0.235, 0.284, 3.232]} rotation={[-Math.PI, 1.56, -Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Cube273.geometry} material={materials['negro_soporte.004']} position={[2.079, 0.284, 2.499]} rotation={[-Math.PI, 0.773, -Math.PI]} scale={0.006} />
      <group position={[-2.823, 0.307, -0.14]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.055, 0.031, 0.002]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.SILVER} />
      </group>
      <group position={[-2.145, 0.307, 1.825]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.055, 0.031, 0.002]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.SILVER} />
      </group>
      <group position={[-0.157, 0.307, 2.847]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.055, 0.031, 0.002]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.SILVER} />
      </group>
      <group position={[1.86, 0.307, 2.172]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.055, 0.031, 0.002]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.SILVER} />
      </group>
      <mesh geometry={nodes.Cube228.geometry} material={materials.NEGRO} position={[-2.841, 0.322, -0.085]} rotation={[0, -1.539, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube243.geometry} material={materials.NEGRO} position={[-2.124, 0.322, 1.879]} rotation={[0, -0.839, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube259.geometry} material={materials.NEGRO} position={[-0.103, 0.322, 2.866]} rotation={[0, 0.017, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube275.geometry} material={materials.NEGRO} position={[1.912, 0.322, 2.147]} rotation={[0, 0.804, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube229.geometry} material={materials.NEGRO} position={[-2.845, 0.322, -0.193]} rotation={[0, -1.539, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube244.geometry} material={materials.NEGRO} position={[-2.196, 0.322, 1.799]} rotation={[0, -0.839, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube260.geometry} material={materials.NEGRO} position={[-0.211, 0.322, 2.868]} rotation={[0, 0.017, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube276.geometry} material={materials.NEGRO} position={[1.838, 0.322, 2.224]} rotation={[0, 0.804, -Math.PI]} scale={[-0.002, -0.046, -0.019]} />
      <mesh geometry={nodes.Cube230.geometry} material={materials.SILVER} position={[-2.843, 0.335, -0.139]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.052, 0.002, 0.019]} />
      <mesh geometry={nodes.Cube245.geometry} material={materials.SILVER} position={[-2.16, 0.335, 1.839]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.052, 0.002, 0.019]} />
      <mesh geometry={nodes.Cube261.geometry} material={materials.SILVER} position={[-0.157, 0.335, 2.867]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.052, 0.002, 0.019]} />
      <mesh geometry={nodes.Cube277.geometry} material={materials.SILVER} position={[1.875, 0.335, 2.186]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.052, 0.002, 0.019]} />
      <mesh geometry={nodes.Cube231.geometry} material={materials.NEGRO} position={[-3.176, 0.325, 0.111]} rotation={[0, -1.539, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube246.geometry} material={materials.NEGRO} position={[-2.254, 0.325, 2.244]} rotation={[0, -0.839, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube262.geometry} material={materials.NEGRO} position={[0.088, 0.325, 3.204]} rotation={[0, 0.017, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube278.geometry} material={materials.NEGRO} position={[2.286, 0.325, 2.25]} rotation={[0, 0.804, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube232.geometry} material={materials.NEGRO} position={[-3.184, 0.325, -0.125]} rotation={[0, -1.539, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube247.geometry} material={materials.NEGRO} position={[-2.411, 0.325, 2.069]} rotation={[0, -0.839, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube263.geometry} material={materials.NEGRO} position={[-0.148, 0.325, 3.208]} rotation={[0, 0.017, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube279.geometry} material={materials.NEGRO} position={[2.123, 0.325, 2.42]} rotation={[0, 0.804, -Math.PI]} scale={[-0.004, -0.051, -0.016]} />
      <mesh geometry={nodes.Cube233.geometry} material={materials.SILVER} position={[-3.181, 0.339, -0.007]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.115, 0.003, 0.017]} />
      <mesh geometry={nodes.Cube248.geometry} material={materials.SILVER} position={[-2.333, 0.339, 2.157]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.115, 0.003, 0.017]} />
      <mesh geometry={nodes.Cube264.geometry} material={materials.SILVER} position={[-0.03, 0.339, 3.207]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.115, 0.003, 0.017]} />
      <mesh geometry={nodes.Cube280.geometry} material={materials.SILVER} position={[2.205, 0.339, 2.336]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.115, 0.003, 0.017]} />
      <mesh geometry={nodes.Cube234.geometry} material={materials.NEGRO} position={[-3.021, 0.521, -0.011]} rotation={[Math.PI, 1.539, Math.PI / 2]} scale={[0.007, 0.167, 0.006]} />
      <mesh geometry={nodes.Cube249.geometry} material={materials.NEGRO} position={[-2.214, 0.521, 2.051]} rotation={[-Math.PI, 0.839, Math.PI / 2]} scale={[0.007, 0.167, 0.006]} />
      <mesh geometry={nodes.Cube265.geometry} material={materials.NEGRO} position={[-0.032, 0.521, 3.047]} rotation={[Math.PI, -0.017, Math.PI / 2]} scale={[0.007, 0.167, 0.006]} />
      <mesh geometry={nodes.Cube281.geometry} material={materials.NEGRO} position={[2.091, 0.521, 2.224]} rotation={[Math.PI, -0.804, Math.PI / 2]} scale={[0.007, 0.167, 0.006]} />
      <mesh geometry={nodes.Cube235.geometry} material={materials.NEGRO} position={[-3.027, 0.4, -0.188]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.006, 0.127, 0.006]} />
      <mesh geometry={nodes.Cube250.geometry} material={materials.NEGRO} position={[-2.332, 0.4, 1.92]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.006, 0.127, 0.006]} />
      <mesh geometry={nodes.Cube266.geometry} material={materials.NEGRO} position={[-0.208, 0.4, 3.05]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.006, 0.127, 0.006]} />
      <mesh geometry={nodes.Cube282.geometry} material={materials.NEGRO} position={[1.968, 0.4, 2.351]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.006, 0.127, 0.006]} />
      <mesh geometry={nodes.Cube236.geometry} material={materials.NEGRO} position={[-3.118, 0.521, -0.185]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.006, 0.006, 0.086]} />
      <mesh geometry={nodes.Cube251.geometry} material={materials.NEGRO} position={[-2.4, 0.521, 1.981]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.006, 0.006, 0.086]} />
      <mesh geometry={nodes.Cube267.geometry} material={materials.NEGRO} position={[-0.207, 0.521, 3.141]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.006, 0.006, 0.086]} />
      <mesh geometry={nodes.Cube283.geometry} material={materials.NEGRO} position={[2.034, 0.521, 2.415]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.006, 0.006, 0.086]} />
      <mesh geometry={nodes.Cube237.geometry} material={materials.SILVER} position={[-3.203, 0.402, -0.006]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.182, 0.126, 0.006]} />
      <mesh geometry={nodes.Cube252.geometry} material={materials.SILVER} position={[-2.349, 0.402, 2.172]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.182, 0.126, 0.006]} />
      <mesh geometry={nodes.Cube268.geometry} material={materials.SILVER} position={[-0.03, 0.402, 3.229]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.182, 0.126, 0.006]} />
      <mesh geometry={nodes.Cube284.geometry} material={materials.SILVER} position={[2.221, 0.402, 2.351]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.182, 0.126, 0.006]} />
      <group position={[-2.822, 0.425, 0.174]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.032, 0.148, 0.011]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.NEGRO} />
      </group>
      <group position={[-1.942, 0.425, 2.064]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.032, 0.148, 0.011]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.NEGRO} />
      </group>
      <group position={[0.156, 0.425, 2.85]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.032, 0.148, 0.011]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.NEGRO} />
      </group>
      <group position={[2.084, 0.425, 1.952]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.032, 0.148, 0.011]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.NEGRO} />
      </group>
      <mesh geometry={nodes.Cube239.geometry} material={materials.SILVER} position={[-3.112, 0.533, -0.007]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.181, 0.006, 0.098]} />
      <mesh geometry={nodes.Cube254.geometry} material={materials.SILVER} position={[-2.281, 0.533, 2.113]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={[0.181, 0.006, 0.098]} />
      <mesh geometry={nodes.Cube270.geometry} material={materials.SILVER} position={[-0.029, 0.533, 3.138]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.181, 0.006, 0.098]} />
      <mesh geometry={nodes.Cube286.geometry} material={materials.SILVER} position={[2.157, 0.533, 2.287]} rotation={[Math.PI, -0.804, Math.PI]} scale={[0.181, 0.006, 0.098]} />
      <mesh geometry={nodes.Environment_PalmTree_1.geometry} material={materials.Atlas} position={[-0.896, 0.095, -0.503]} rotation={[Math.PI / 2, 0, 0]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1001.geometry} material={materials.Atlas} position={[-1.034, 0.095, 0.516]} rotation={[Math.PI / 2, 0, 1.19]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1002.geometry} material={materials.Atlas} position={[-0.401, 0.095, 1.098]} rotation={[Math.PI / 2, 0, 2.952]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1003.geometry} material={materials.Atlas} position={[0.432, 0.095, 0.956]} rotation={[Math.PI / 2, 0, 1.216]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1004.geometry} material={materials.Atlas} position={[0.984, 0.095, 0.324]} rotation={[Math.PI / 2, 0, 2.591]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1005.geometry} material={materials.Atlas} position={[0.963, 0.095, -0.426]} rotation={[Math.PI / 2, 0, -0.046]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1006.geometry} material={materials.Atlas} position={[0.414, 0.095, -1.064]} rotation={[Math.PI / 2, 0, 0.891]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1007.geometry} material={materials.Atlas} position={[-0.492, 0.095, -0.875]} rotation={[Math.PI / 2, 0, -0.247]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1008.geometry} material={materials.Atlas} position={[0.056, 0.095, -1.708]} rotation={[Math.PI / 2, 0, -0.042]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1009.geometry} material={materials.Atlas} position={[1.69, 0.095, -0.007]} rotation={[Math.PI / 2, 0, 1.452]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1010.geometry} material={materials.Atlas} position={[0.71, 0.037, 1.827]} rotation={[Math.PI / 2, 0, -3.099]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1011.geometry} material={materials.Atlas} position={[-1.016, 0.039, 1.637]} rotation={[Math.PI / 2, 0, 2.545]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1012.geometry} material={materials.Atlas} position={[-1.575, 0.066, 1.107]} rotation={[Math.PI / 2, 0, -2.381]} scale={0.078} />
      <mesh geometry={nodes.Environment_PalmTree_1013.geometry} material={materials.Atlas} position={[-1.595, 0.052, -1.092]} rotation={[Math.PI / 2, 0, -1.868]} scale={0.078} />
    </group>
  </RigidBody>
     
   )
 }
 
 export default Base;
 
 useGLTF.preload('/models/base.glb')
 
