/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/base.glb -o src/components/Base.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Base(props) {
  const { nodes, materials } = useGLTF('/models/base.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" name="ground" colliders="trimesh">
      
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.342, 0.279, 0.121]} scale={0.628} />
      <mesh geometry={nodes.Cube.geometry} material={materials.MATERIAL_BRONCE} position={[0.342, 0.133, -44.685]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.MATERIAL_BRONCE} position={[0.342, 0.133, 44.826]} rotation={[-Math.PI, 0.015, -Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.MATERIAL_BRONCE} position={[-44.007, 0.133, 0.082]} rotation={[0, 1.551, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.MATERIAL_BRONCE} position={[45.815, 0.133, 0.082]} rotation={[0, -1.559, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.MATERIAL_BRONCE} position={[-31.032, 0.133, 31.472]} rotation={[-Math.PI, 0.764, -Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.MATERIAL_BRONCE} position={[30.776, 0.133, -32.749]} rotation={[0, -0.716, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.MATERIAL_BRONCE} position={[-31.791, 0.133, -31.162]} rotation={[0, 0.793, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.MATERIAL_BRONCE} position={[32.043, 0.133, 31.841]} rotation={[Math.PI, -0.803, Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0.342, 0.279, 0.121]} scale={0.628} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[0.342, 0.279, 0.121]} scale={0.628} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.MATERIAL_BRONCE} position={[0.342, 0.133, -44.685]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.MATERIAL_BRONCE} position={[0.342, 0.133, 44.826]} rotation={[-Math.PI, 0.015, -Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.MATERIAL_BRONCE} position={[-44.007, 0.133, 0.082]} rotation={[0, 1.551, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.MATERIAL_BRONCE} position={[45.815, 0.133, 0.082]} rotation={[0, -1.559, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.MATERIAL_BRONCE} position={[-31.032, 0.133, 31.472]} rotation={[-Math.PI, 0.764, -Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.MATERIAL_BRONCE} position={[30.776, 0.133, -32.749]} rotation={[0, -0.716, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.MATERIAL_BRONCE} position={[-31.791, 0.133, -31.162]} rotation={[0, 0.793, 0]} scale={[7.591, 11.314, 6.409]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.MATERIAL_BRONCE} position={[32.043, 0.133, 31.841]} rotation={[Math.PI, -0.803, Math.PI]} scale={[7.591, 11.314, 6.409]} />
      <group position={[0.342, 0.279, 0.121]} scale={0.628}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder003_4.geometry} material={materials['CIRCULO EXTERIOR']} />
        <mesh geometry={nodes.Cylinder003_5.geometry} material={materials['Material_parte de abajo']} />
      </group>
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-0.508, -20.391, -1.566]} rotation={[0, 1.157, 0]} scale={0.498} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.MATERIAL_BRONCE} position={[-33.042, -20.507, -15.864]} rotation={[0, 1.157, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.MATERIAL_BRONCE} position={[31.952, -20.507, 12.699]} rotation={[Math.PI, -1.142, Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.MATERIAL_BRONCE} position={[-14.688, -20.507, 30.623]} rotation={[-Math.PI, 0.433, -Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.MATERIAL_BRONCE} position={[13.973, -20.507, -34.597]} rotation={[0, -0.402, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.MATERIAL_BRONCE} position={[12.244, -20.507, 31.218]} rotation={[Math.PI, -0.393, Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.MATERIAL_BRONCE} position={[-14.664, -20.507, -34.153]} rotation={[0, 0.44, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.MATERIAL_BRONCE} position={[-33.476, -20.507, 11.783]} rotation={[-Math.PI, 1.192, -Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.MATERIAL_BRONCE} position={[32.639, -20.507, -14.463]} rotation={[0, -1.182, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-0.508, -20.391, -1.566]} rotation={[0, 1.157, 0]} scale={0.498} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-0.508, -20.391, -1.566]} rotation={[0, 1.157, 0]} scale={0.498} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.MATERIAL_BRONCE} position={[-33.042, -20.507, -15.864]} rotation={[0, 1.157, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.MATERIAL_BRONCE} position={[31.952, -20.507, 12.699]} rotation={[Math.PI, -1.142, Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.MATERIAL_BRONCE} position={[-14.688, -20.507, 30.623]} rotation={[-Math.PI, 0.433, -Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.MATERIAL_BRONCE} position={[13.973, -20.507, -34.597]} rotation={[0, -0.402, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.MATERIAL_BRONCE} position={[12.244, -20.507, 31.218]} rotation={[Math.PI, -0.393, Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.MATERIAL_BRONCE} position={[-14.664, -20.507, -34.153]} rotation={[0, 0.44, 0]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.MATERIAL_BRONCE} position={[-33.476, -20.507, 11.783]} rotation={[-Math.PI, 1.192, -Math.PI]} scale={[6.021, 8.973, 5.083]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.MATERIAL_BRONCE} position={[32.639, -20.507, -14.463]} rotation={[0, -1.182, 0]} scale={[6.021, 8.973, 5.083]} />
      <group position={[-0.508, -20.391, -1.566]} rotation={[0, 1.157, 0]} scale={0.498}>
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder007_3.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder007_4.geometry} material={materials['CIRCULO EXTERIOR']} />
        <mesh geometry={nodes.Cylinder007_5.geometry} material={materials['Material_parte de abajo']} />
      </group>
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-1.051, -37.636, -0.354]} rotation={[0, 0.658, 0]} scale={0.39} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.MATERIAL_BRONCE} position={[-18.041, -37.727, -22.357]} rotation={[0, 0.658, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.MATERIAL_BRONCE} position={[15.901, -37.727, 21.599]} rotation={[Math.PI, -0.643, Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.MATERIAL_BRONCE} position={[-22.844, -37.727, 16.444]} rotation={[-Math.PI, 0.933, -Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.MATERIAL_BRONCE} position={[21.265, -37.727, -17.616]} rotation={[0, -0.902, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.MATERIAL_BRONCE} position={[-4.57, -37.727, 26.938]} rotation={[-Math.PI, 0.106, -Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.MATERIAL_BRONCE} position={[1.43, -37.727, -28.036]} rotation={[0, -0.059, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials.MATERIAL_BRONCE} position={[-28.693, -37.727, -3.532]} rotation={[0, 1.45, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials.MATERIAL_BRONCE} position={[26.544, -37.727, 3.202]} rotation={[Math.PI, -1.461, Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-1.051, -37.636, -0.354]} rotation={[0, 0.658, 0]} scale={0.39} />
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-1.051, -37.636, -0.354]} rotation={[0, 0.658, 0]} scale={0.39} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.MATERIAL_BRONCE} position={[-18.041, -37.727, -22.357]} rotation={[0, 0.658, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.MATERIAL_BRONCE} position={[15.901, -37.727, 21.599]} rotation={[Math.PI, -0.643, Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.MATERIAL_BRONCE} position={[-22.844, -37.727, 16.444]} rotation={[-Math.PI, 0.933, -Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.MATERIAL_BRONCE} position={[21.265, -37.727, -17.616]} rotation={[0, -0.902, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.MATERIAL_BRONCE} position={[-4.57, -37.727, 26.938]} rotation={[-Math.PI, 0.106, -Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.MATERIAL_BRONCE} position={[1.43, -37.727, -28.036]} rotation={[0, -0.059, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.MATERIAL_BRONCE} position={[-28.693, -37.727, -3.532]} rotation={[0, 1.45, 0]} scale={[4.71, 7.019, 3.976]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.MATERIAL_BRONCE} position={[26.544, -37.727, 3.202]} rotation={[Math.PI, -1.461, Math.PI]} scale={[4.71, 7.019, 3.976]} />
      <group position={[-1.051, -37.636, -0.354]} rotation={[0, 0.658, 0]} scale={0.39}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials.MATERIAL_VIDRIO} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['CIRCULO EXTERIOR']} />
        <mesh geometry={nodes.Cylinder011_5.geometry} material={materials['Material_parte de abajo']} />
      </group>
      </RigidBody>
      
    </group>
  )
}
export default Base; // Asegúrate de exportar por defecto

useGLTF.preload('/models/base.glb')
