/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/base.glb -o src/components/Base.jsx -r public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

export function Base(props) {
  const { scene } = useGLTF('/models/base.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
                    <RigidBody type="fixed" name="ground" colliders="trimesh">
      
      <group position={[0.177, 0, 0]} scale={0.013}>
        <primitive object={nodes.Bone} />
      </group>
      <mesh geometry={nodes.barra.geometry} material={materials.material_estructura_torre} position={[3.147, 0.367, -0.005]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.082, 0.082, 0.097]} />
      <mesh geometry={nodes.cafeteria.geometry} material={materials.material_piedra} position={[3.147, 0.367, -0.005]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.082, 0.082, 0.097]} />
      <mesh geometry={nodes.Lampara_iluminacion.geometry} material={materials['material farolas']} position={[3.169, 0.437, -0.041]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <mesh geometry={nodes.Lampara_iluminacion001.geometry} material={materials['material farolas']} position={[3.167, 0.437, -0.003]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <mesh geometry={nodes.Lampara_iluminacion002.geometry} material={materials['material farolas']} position={[3.165, 0.437, 0.036]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <group position={[0.023, 0.111, -0.015]} scale={0.194}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['metal.002']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Azul_pantalla.002']} />
      </group>
      <group position={[0, 0.102, 0]} scale={[1.72, 24.125, 1.72]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0, -0.016, 0]} scale={68.367} />
      <mesh geometry={nodes.walkroad.geometry} material={materials.color_Palette} position={[0.007, 0.11, -0.055]} scale={[0.19, 0.037, 0.181]} />
      <mesh geometry={nodes.walkroad001.geometry} material={materials.color_Palette} position={[0.026, 0.11, 0.03]} rotation={[-Math.PI, 0.019, -Math.PI]} scale={[0.19, 0.037, 0.181]} />
      <mesh geometry={nodes.walkroad002.geometry} material={materials.color_Palette} position={[0.041, 0.102, 1.705]} rotation={[0, 1.531, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.stone003.geometry} material={materials.Mat_tree} position={[1.605, 0.064, -0.906]} rotation={[Math.PI, -1.459, Math.PI]} scale={0.103} />
      <mesh geometry={nodes.stone002.geometry} material={materials.Mat_tree} position={[1.654, 0.065, -0.799]} rotation={[0, 1.385, 0]} scale={0.103} />
      <mesh geometry={nodes.stone001.geometry} material={materials.Mat_tree} position={[1.751, 0.065, -0.521]} rotation={[0, -0.994, 0]} scale={0.103} />
      <mesh geometry={nodes.stone004.geometry} material={materials.Mat_tree} position={[1.697, 0.064, -0.654]} rotation={[Math.PI, -1.459, Math.PI]} scale={0.103} />
      <mesh geometry={nodes.walkroad003.geometry} material={materials['color_Palette.003']} position={[0.034, 0.102, 1.365]} rotation={[-Math.PI, 1.526, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad004.geometry} material={materials['color_Palette.004']} position={[0.05, 0.102, 1.042]} rotation={[0, 1.406, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad005.geometry} material={materials['color_Palette.005']} position={[1.722, 0.102, -0.079]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad006.geometry} material={materials['color_Palette.006']} position={[-0.366, 0.102, 1.353]} rotation={[0, -0.596, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad007.geometry} material={materials['color_Palette.007']} position={[-0.653, 0.102, 1.212]} rotation={[0, -0.241, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad008.geometry} material={materials['color_Palette.008']} position={[-1.211, 0.102, 1.183]} rotation={[0, 0.589, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad009.geometry} material={materials['color_Palette.009']} position={[-0.994, 0.102, 1.066]} rotation={[0, -0.747, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad010.geometry} material={materials['color_Palette.010']} position={[0.253, 0.102, 1.41]} rotation={[0, 0.198, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad011.geometry} material={materials['color_Palette.011']} position={[0.571, 0.102, 1.221]} rotation={[0, 0.703, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad012.geometry} material={materials['color_Palette.012']} position={[0.87, 0.102, 0.965]} rotation={[Math.PI, -0.088, Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad013.geometry} material={materials['color_Palette.013']} position={[1.215, 0.102, 1.149]} rotation={[-Math.PI, 0.995, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad014.geometry} material={materials['color_Palette.005']} position={[-1.713, 0.102, 0.092]} rotation={[0, -0.027, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad015.geometry} material={materials.color_Palette} position={[0.123, 0.102, -1.683]} rotation={[0, 1.531, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad016.geometry} material={materials['color_Palette.008']} position={[1.211, 0.102, -1.146]} rotation={[0, 0.687, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad017.geometry} material={materials['color_Palette.013']} position={[-1.028, 0.102, -1.294]} rotation={[-Math.PI, 0.995, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad018.geometry} material={materials['color_Palette.006']} position={[-1.193, 0.102, 0.735]} rotation={[0, -1.333, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad019.geometry} material={materials['color_Palette.007']} position={[-1.311, 0.102, 0.437]} rotation={[0, -0.978, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad020.geometry} material={materials['color_Palette.009']} position={[-1.465, 0.102, 0.099]} rotation={[0, -1.483, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad021.geometry} material={materials['color_Palette.006']} position={[-1.416, 0.102, -0.32]} rotation={[Math.PI, -0.922, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad022.geometry} material={materials['color_Palette.007']} position={[-1.255, 0.102, -0.609]} rotation={[Math.PI, -1.277, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad023.geometry} material={materials['color_Palette.009']} position={[-1.085, 0.102, -0.953]} rotation={[Math.PI, -0.772, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad024.geometry} material={materials['color_Palette.006']} position={[-0.745, 0.102, -1.186]} rotation={[Math.PI, -0.199, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad025.geometry} material={materials['color_Palette.007']} position={[-0.417, 0.102, -1.319]} rotation={[Math.PI, -0.274, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad026.geometry} material={materials['color_Palette.009']} position={[-0.078, 0.102, -1.442]} rotation={[Math.PI, -0.049, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad027.geometry} material={materials['color_Palette.006']} position={[0.316, 0.102, -1.383]} rotation={[-Math.PI, 0.626, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad028.geometry} material={materials['color_Palette.007']} position={[0.641, 0.102, -1.237]} rotation={[-Math.PI, 0.568, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad029.geometry} material={materials['color_Palette.009']} position={[0.956, 0.102, -1.067]} rotation={[-Math.PI, 0.776, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad030.geometry} material={materials['color_Palette.006']} position={[1.182, 0.102, -0.777]} rotation={[-Math.PI, 1.153, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad031.geometry} material={materials['color_Palette.007']} position={[1.342, 0.102, -0.452]} rotation={[-Math.PI, 1.248, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad032.geometry} material={materials['color_Palette.009']} position={[1.478, 0.102, -0.107]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad033.geometry} material={materials['color_Palette.006']} position={[1.419, 0.102, 0.249]} rotation={[0, 0.981, 0]} scale={[0.158, 0.046, 0.178]} />
      <mesh geometry={nodes.walkroad034.geometry} material={materials['color_Palette.007']} position={[1.292, 0.102, 0.513]} rotation={[0, 1.336, 0]} scale={[0.158, 0.046, 0.178]} />
      <mesh geometry={nodes.walkroad035.geometry} material={materials['color_Palette.009']} position={[1.16, 0.102, 0.826]} rotation={[0, 0.831, 0]} scale={[0.158, 0.046, 0.178]} />
      <mesh geometry={nodes.walkroad036.geometry} material={materials['color_Palette.005']} position={[1.122, 0.102, -0.079]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad037.geometry} material={materials['color_Palette.005']} position={[-1.108, 0.102, -0.042]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad038.geometry} material={materials.color_Palette} position={[0.123, 0.102, -1.098]} rotation={[0, 1.531, 0]} scale={[0.173, 0.05, 0.195]} />
      <mesh geometry={nodes.walkroad039.geometry} material={materials['color_Palette.006']} position={[-0.23, 0.102, 0.795]} rotation={[0, -0.741, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad040.geometry} material={materials['color_Palette.007']} position={[-0.5, 0.102, 0.598]} rotation={[0, -0.467, 0]} scale={[0.155, 0.045, 0.175]} />
      <mesh geometry={nodes.walkroad041.geometry} material={materials['color_Palette.009']} position={[-0.783, 0.102, 0.357]} rotation={[0, -1.278, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad042.geometry} material={materials['color_Palette.009']} position={[-0.763, 0.102, 0.023]} rotation={[0, 1.49, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad043.geometry} material={materials['color_Palette.006']} position={[-0.848, 0.102, -0.354]} rotation={[Math.PI, -0.783, Math.PI]} scale={[0.152, 0.044, 0.171]} />
      <mesh geometry={nodes.walkroad044.geometry} material={materials['color_Palette.007']} position={[-0.689, 0.102, -0.658]} rotation={[Math.PI, -0.988, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad045.geometry} material={materials['color_Palette.009']} position={[-0.375, 0.102, -0.86]} rotation={[Math.PI, -0.177, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad046.geometry} material={materials['color_Palette.009']} position={[-0.043, 0.102, -0.764]} rotation={[0, -0.197, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad048.geometry} material={materials['color_Palette.007']} position={[0.622, 0.102, -0.697]} rotation={[-Math.PI, 0.689, -Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad049.geometry} material={materials['color_Palette.009']} position={[0.809, 0.102, -0.365]} rotation={[0, 1.562, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad050.geometry} material={materials['color_Palette.009']} position={[0.725, 0.102, -0.035]} rotation={[Math.PI, -1.434, Math.PI]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad051.geometry} material={materials['color_Palette.006']} position={[0.76, 0.102, 0.346]} rotation={[0, 0.727, 0]} scale={[0.152, 0.044, 0.171]} />
      <mesh geometry={nodes.walkroad052.geometry} material={materials['color_Palette.007']} position={[0.53, 0.102, 0.605]} rotation={[0, 0.513, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad053.geometry} material={materials['color_Palette.009']} position={[0.205, 0.102, 0.795]} rotation={[0, 0.293, 0]} scale={[0.179, 0.052, 0.202]} />
      <mesh geometry={nodes.walkroad047.geometry} material={materials['color_Palette.007']} position={[0.34, 0.102, -0.841]} rotation={[-Math.PI, 0.413, -Math.PI]} scale={[0.156, 0.045, 0.176]} />
      <mesh geometry={nodes.walkroad054.geometry} material={materials['color_Palette.008']} position={[-0.385, 0.102, 0.238]} rotation={[Math.PI, -0.544, Math.PI]} scale={[0.158, 0.046, 0.178]} />
      <mesh geometry={nodes.walkroad055.geometry} material={materials['color_Palette.008']} position={[0.395, 0.102, -0.385]} rotation={[Math.PI, -0.544, Math.PI]} scale={[0.151, 0.044, 0.17]} />
      <mesh geometry={nodes.walkroad056.geometry} material={materials['color_Palette.008']} position={[0.254, 0.102, 0.335]} rotation={[0, -1.028, 0]} scale={[0.131, 0.038, 0.148]} />
      <mesh geometry={nodes.walkroad057.geometry} material={materials['color_Palette.008']} position={[-0.358, 0.102, -0.417]} rotation={[0, -1.061, 0]} scale={[0.148, 0.043, 0.167]} />
      <mesh geometry={nodes.bush1.geometry} material={materials['color_Palette.015']} position={[-0.903, 0.091, 0.813]} rotation={[0, -1.326, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1001.geometry} material={materials['color_Palette.015']} position={[-0.656, 0.091, 0.671]} rotation={[0, -1.326, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1002.geometry} material={materials['color_Palette.015']} position={[0.735, 0.091, 0.607]} rotation={[Math.PI, -0.011, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1003.geometry} material={materials['color_Palette.015']} position={[0.816, 0.091, 0.88]} rotation={[Math.PI, -0.011, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1004.geometry} material={materials['color_Palette.015']} position={[0.69, 0.091, -0.675]} rotation={[0, -1.41, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1005.geometry} material={materials['color_Palette.015']} position={[0.948, 0.091, -0.796]} rotation={[0, -1.41, 0]} scale={0.097} />
     <mesh geometry={nodes.bush1006.geometry} material={materials['color_Palette.015']} position={[-0.814, 0.103, -0.751]} rotation={[0, -0.728, 0]} scale={0.077} />
      <mesh geometry={nodes.bush1007.geometry} material={materials['color_Palette.015']} position={[-0.715, 0.103, -0.956]} rotation={[0, -0.728, 0]} scale={0.077} />
      <mesh geometry={nodes.bush1008.geometry} material={materials['color_Palette.015']} position={[0.984, 0.091, 0.134]} rotation={[Math.PI, -0.011, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1009.geometry} material={materials['color_Palette.015']} position={[0.123, 0.091, 0.983]} rotation={[-Math.PI, 1.485, -Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1010.geometry} material={materials['color_Palette.015']} position={[-0.172, 0.091, 0.983]} rotation={[-Math.PI, 1.485, -Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1011.geometry} material={materials['color_Palette.015']} position={[-0.993, 0.091, 0.151]} rotation={[0, 0.355, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1012.geometry} material={materials['color_Palette.015']} position={[-1.038, 0.091, -0.116]} rotation={[0, 0.14, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1013.geometry} material={materials['color_Palette.015']} position={[-0.116, 0.1, -1.026]} rotation={[0, -1.41, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1014.geometry} material={materials['color_Palette.015']} position={[0.181, 0.1, -1.026]} rotation={[0, -1.41, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1015.geometry} material={materials['color_Palette.015']} position={[0.984, 0.091, -0.161]} rotation={[Math.PI, -0.364, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1019.geometry} material={materials['color_Palette.015']} position={[0.249, 0.091, -0.403]} rotation={[0, -0.457, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1020.geometry} material={materials['color_Palette.015']} position={[0.304, 0.091, -0.455]} rotation={[0, -1.437, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1021.geometry} material={materials['color_Palette.015']} position={[-0.162, 0.091, -0.492]} rotation={[0, -0.473, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1022.geometry} material={materials['color_Palette.015']} position={[-0.199, 0.091, -0.57]} rotation={[0, -0.473, 0]} scale={0.074} />
      <mesh geometry={nodes.bush1026.geometry} material={materials['color_Palette.015']} position={[-0.342, 0.091, -0.27]} rotation={[0, 1.2, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1027.geometry} material={materials['color_Palette.015']} position={[-0.398, 0.091, -0.32]} rotation={[0, 0.219, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1028.geometry} material={materials['color_Palette.015']} position={[-0.396, 0.091, 0.148]} rotation={[0, 1.183, 0]} scale={0.097} />
      <mesh geometry={nodes.bush1029.geometry} material={materials['color_Palette.015']} position={[-0.47, 0.091, 0.192]} rotation={[0, 1.183, 0]} scale={0.074} />
      <mesh geometry={nodes.bush1033.geometry} material={materials['color_Palette.015']} position={[0.392, 0.091, 0.24]} rotation={[Math.PI, -1.16, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1034.geometry} material={materials['color_Palette.015']} position={[0.448, 0.091, 0.292]} rotation={[Math.PI, -0.179, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1035.geometry} material={materials['color_Palette.015']} position={[0.433, 0.091, -0.175]} rotation={[Math.PI, -1.143, Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1036.geometry} material={materials['color_Palette.015']} position={[0.509, 0.091, -0.209]} rotation={[Math.PI, -1.143, Math.PI]} scale={0.074} />
      <mesh geometry={nodes.bush1040.geometry} material={materials['color_Palette.015']} position={[-0.242, 0.091, 0.398]} rotation={[-Math.PI, 1.319, -Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1041.geometry} material={materials['color_Palette.015']} position={[0.205, 0.091, 0.407]} rotation={[-Math.PI, 0.355, -Math.PI]} scale={0.097} />
      <mesh geometry={nodes.bush1042.geometry} material={materials['color_Palette.015']} position={[0.252, 0.091, 0.48]} rotation={[-Math.PI, 0.355, -Math.PI]} scale={0.074} />
      <group position={[-0.023, 0.187, 2.187]} rotation={[2.878, 0, -Math.PI]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube062.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube062_1.geometry} material={materials.Material_puente_madera} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.material_molde_punto_info} position={[0.025, 0.104, -0.009]} scale={[0.245, 0.002, 0.245]} />
      <group position={[-0.002, 0.045, 3.026]} rotation={[0, -0.075, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-1.607, 0.187, 1.458]} rotation={[2.768, 0.777, -2.873]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-2.202, 0.045, 2.05]} rotation={[0, -0.888, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder008_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder008_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder008_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[1.487, 0.187, 1.57]} rotation={[2.801, -0.676, 2.924]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[2.046, 0.045, 2.195]} rotation={[0, 0.63, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder009_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder009_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder009_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder009_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[2.18, 0.187, -0.002]} rotation={[1.652, -1.307, 1.655]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[3.019, 0.045, -0.004]} rotation={[0, 1.474, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder010_2.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder010_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder010_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder010_5.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-2.176, 0.187, 0.003]} rotation={[1.424, 1.305, -1.419]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-3.015, 0.045, -0.009]} rotation={[Math.PI, -1.456, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[0.059, 0.187, -2.195]} rotation={[0.263, 0.009, -0.002]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[0.03, 0.045, -3.034]} rotation={[-Math.PI, 0.066, -Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder012.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder012_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder012_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-1.402, 0.187, -1.643]} rotation={[0.336, 0.661, -0.211]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-1.952, 0.045, -2.277]} rotation={[Math.PI, -0.615, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder013_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder013_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[1.536, 0.187, -1.553]} rotation={[0.368, -0.762, 0.26]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[2.121, 0.045, -2.155]} rotation={[-Math.PI, 0.871, -Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder014_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder014_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[2.133, 0.279, -2.157]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.377, 0.002, 0.377]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} position={[2.306, 0.386, -2.344]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.011, 0.032, 0.204]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.material_estructura_torre} position={[2.094, 0.385, -2.432]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.092, 0.032, 0.01]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.material_piedra} position={[2.222, 0.553, -2.25]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.137, 0.013, 0.228]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.013']} position={[2.343, 0.341, -2.026]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.032, 0.013, 0.021]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.material_piedra} position={[2.305, 0.329, -1.985]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.001, 0.001, 0.02]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.013']} position={[1.986, 0.341, -2.364]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.032, 0.013, 0.021]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.material_piedra} position={[1.948, 0.329, -2.323]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.001, 0.001, 0.02]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.material_estructura_torre} position={[2.222, 0.34, -2.25]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.137, 0.013, 0.228]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.material_piedra} position={[2.042, 0.279, -2.065]} rotation={[Math.PI, -0.812, Math.PI]} scale={[-0.002, -0.002, -0.227]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.material_estructura_torre} position={[2.193, 0.303, -2.224]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.046, 0.007, 0.077]} />
      <mesh geometry={nodes.Tronco1.geometry} material={materials['Madera_color_1.002']} position={[-1.775, 0.139, -0.264]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1.geometry} material={materials['Arbol_Color1.002']} position={[-1.774, 0.393, -0.264]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1001.geometry} material={materials['Madera_color_1.002']} position={[-1.775, 0.139, 0.252]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1001.geometry} material={materials['Arbol_Color1.002']} position={[-1.774, 0.393, 0.252]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1002.geometry} material={materials['Madera_color_1.002']} position={[1.758, 0.139, -0.264]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1002.geometry} material={materials['Arbol_Color1.002']} position={[1.759, 0.393, -0.264]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1003.geometry} material={materials['Madera_color_1.002']} position={[1.758, 0.139, 0.252]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1003.geometry} material={materials['Arbol_Color1.002']} position={[1.759, 0.393, 0.252]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1004.geometry} material={materials['Madera_color_1.002']} position={[1.415, 0.139, 1.077]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1004.geometry} material={materials['Arbol_Color1.002']} position={[1.416, 0.393, 1.077]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1005.geometry} material={materials['Madera_color_1.002']} position={[-1.447, 0.139, 1.025]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1005.geometry} material={materials['Arbol_Color1.002']} position={[-1.446, 0.393, 1.025]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1006.geometry} material={materials['Madera_color_1.002']} position={[0.204, 0.139, 1.731]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1006.geometry} material={materials['Arbol_Color1.002']} position={[0.204, 0.393, 1.731]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1007.geometry} material={materials['Madera_color_1.002']} position={[-0.265, 0.139, 1.731]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1007.geometry} material={materials['Arbol_Color1.002']} position={[-0.264, 0.393, 1.731]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1008.geometry} material={materials['Madera_color_1.002']} position={[-1.343, 0.139, -1.138]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1008.geometry} material={materials['Arbol_Color1.002']} position={[-1.342, 0.393, -1.138]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1009.geometry} material={materials['Madera_color_1.002']} position={[-0.983, 0.139, -1.507]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1009.geometry} material={materials['Arbol_Color1.002']} position={[-0.982, 0.393, -1.507]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1010.geometry} material={materials['Madera_color_1.002']} position={[-0.201, 0.139, -1.769]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1010.geometry} material={materials['Arbol_Color1.002']} position={[-0.2, 0.393, -1.769]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1011.geometry} material={materials['Madera_color_1.002']} position={[0.275, 0.139, -1.769]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1011.geometry} material={materials['Arbol_Color1.002']} position={[0.275, 0.393, -1.769]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1012.geometry} material={materials['Madera_color_1.002']} position={[1.064, 0.139, -1.435]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1012.geometry} material={materials['Arbol_Color1.002']} position={[1.065, 0.393, -1.435]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1013.geometry} material={materials['Madera_color_1.002']} position={[1.436, 0.139, -1.085]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1013.geometry} material={materials['Arbol_Color1.002']} position={[1.436, 0.393, -1.085]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1014.geometry} material={materials['Madera_color_1.002']} position={[1.036, 0.139, 1.418]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1014.geometry} material={materials['Arbol_Color1.002']} position={[1.037, 0.393, 1.418]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1015.geometry} material={materials['Madera_color_1.002']} position={[-1.109, 0.139, 1.376]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1015.geometry} material={materials['Arbol_Color1.002']} position={[-1.108, 0.393, 1.376]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1016.geometry} material={materials['Madera_color_1.002']} position={[-0.809, 0.139, 0.865]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1016.geometry} material={materials['Arbol_Color1.002']} position={[-0.809, 0.393, 0.865]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1017.geometry} material={materials['Madera_color_1.002']} position={[-0.765, 0.139, 0.597]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1017.geometry} material={materials['Arbol_Color1.002']} position={[-0.764, 0.393, 0.597]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1018.geometry} material={materials['Madera_color_1.002']} position={[0.926, 0.139, 0.817]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1018.geometry} material={materials['Arbol_Color1.002']} position={[0.927, 0.393, 0.817]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1019.geometry} material={materials['Madera_color_1.002']} position={[0.678, 0.139, 0.698]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1019.geometry} material={materials['Arbol_Color1.002']} position={[0.678, 0.393, 0.698]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1020.geometry} material={materials['Madera_color_1.002']} position={[0.86, 0.139, -0.845]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1020.geometry} material={materials['Arbol_Color1.002']} position={[0.861, 0.393, -0.845]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1021.geometry} material={materials['Madera_color_1.002']} position={[0.784, 0.139, -0.649]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1021.geometry} material={materials['Arbol_Color1.002']} position={[0.785, 0.393, -0.649]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1022.geometry} material={materials['Madera_color_1.002']} position={[-0.73, 0.139, -0.767]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1022.geometry} material={materials['Arbol_Color1.002']} position={[-0.73, 0.393, -0.767]} scale={[0.092, 0.125, 0.092]} />
      <mesh geometry={nodes.Tronco1023.geometry} material={materials['Madera_color_1.002']} position={[-0.81, 0.139, -0.945]} scale={[0.029, 0.038, 0.029]} />
      <mesh geometry={nodes.Copa_arbol1023.geometry} material={materials['Arbol_Color1.002']} position={[-0.809, 0.393, -0.945]} scale={[0.092, 0.125, 0.092]} />
                  </RigidBody>
        
     
    </group>
  )
}


export default Base;
useGLTF.preload('/models/base.glb')
