/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/base.glb -o src/components/Base.jsx -r public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier';

export function Base(props) {
  const { scene } = useGLTF('/models/base.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
            <RigidBody type="fixed" name="ground" colliders="trimesh">
    
    <group {...props} dispose={null}>
      <group position={[0.177, 0, 0]} scale={0.013}>
        <primitive object={nodes.Bone} />
      </group>
      <mesh geometry={nodes.barra.geometry} material={materials.material_estructura_torre} position={[3.163, 0.367, 0.013]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.082, 0.082, 0.097]} />
      <mesh geometry={nodes.cafeteria.geometry} material={materials.material_piedra} position={[3.163, 0.367, 0.013]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.082, 0.082, 0.097]} />
      <mesh geometry={nodes.Lampara_iluminacion.geometry} material={materials['material farolas']} position={[3.185, 0.437, -0.023]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <mesh geometry={nodes.Lampara_iluminacion001.geometry} material={materials['material farolas']} position={[3.183, 0.437, 0.015]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <mesh geometry={nodes.Lampara_iluminacion002.geometry} material={materials['material farolas']} position={[3.181, 0.437, 0.054]} rotation={[-Math.PI, 0.056, -Math.PI]} scale={[0.165, 0.165, 0.195]} />
      <group position={[0, 0.102, 0]} scale={[1.72, 24.125, 1.72]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Material} />
      </group>
      <group position={[0, 0.102, 0]} scale={[1.72, 24.125, 1.72]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0, 0.013, 0]} scale={68.367} />
      <group position={[-3.015, 0.045, 0.008]} rotation={[Math.PI, -1.486, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-2.202, 0.044, 2.051]} rotation={[0, -0.911, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-0.024, 0.044, 3.038]} rotation={[0, -0.094, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[0.038, 0.043, -3.038]} rotation={[-Math.PI, 0.089, -Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[3.038, 0.042, 0.018]} rotation={[0, 1.466, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[2.152, 0.044, -2.131]} rotation={[-Math.PI, 0.901, -Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[-2.005, 0.043, -2.292]} rotation={[Math.PI, -0.571, Math.PI]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[2.08, 0.043, 2.2]} rotation={[0, 0.679, 0]} scale={[0.583, 0.232, 0.583]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.material_estructura_torre} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.material_corona_bake} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials.material_estructura_torre} />
      </group>
      <group position={[0.049, 0.187, -2.195]} rotation={[0.263, 0.009, -0.002]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[1.555, 0.187, -1.537]} rotation={[0.357, -0.731, 0.244]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[2.193, 0.187, 0.019]} rotation={[1.466, -1.306, 1.462]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[1.482, 0.185, 1.607]} rotation={[2.778, -0.749, 2.888]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-0.032, 0.187, 2.195]} rotation={[2.878, -0.023, 3.135]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-1.595, 0.187, 1.472]} rotation={[2.773, 0.764, -2.88]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-2.176, 0.187, -0.009]} rotation={[1.695, 1.305, -1.699]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <group position={[-1.471, 0.187, -1.624]} rotation={[0.335, 0.658, -0.21]} scale={[-0.135, -0.01, -0.303]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.material_piedra} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material_puente_madera} />
      </group>
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[2.133, 0.279, -2.157]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.377, 0.002, 0.377]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.material_piedra} position={[2.306, 0.386, -2.344]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.011, 0.032, 0.204]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.material_estructura_torre} position={[2.094, 0.385, -2.432]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.092, 0.032, 0.01]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.material_piedra} position={[2.222, 0.553, -2.25]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.137, 0.013, 0.228]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.013']} position={[2.343, 0.341, -2.026]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.032, 0.013, 0.021]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.material_piedra} position={[2.305, 0.329, -1.985]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.001, 0.001, 0.02]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.013']} position={[1.986, 0.341, -2.364]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.032, 0.013, 0.021]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.material_piedra} position={[1.948, 0.329, -2.323]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.001, 0.001, 0.02]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.material_estructura_torre} position={[2.222, 0.34, -2.25]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.137, 0.013, 0.228]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.material_piedra} position={[2.042, 0.279, -2.065]} rotation={[Math.PI, -0.812, Math.PI]} scale={[-0.002, -0.002, -0.227]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.material_estructura_torre} position={[2.193, 0.303, -2.224]} rotation={[Math.PI, -0.812, Math.PI]} scale={[0.046, 0.007, 0.077]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.003']} position={[3.036, 0.279, 0.02]} rotation={[0, -0.056, 0]} scale={[-0.276, -0.005, -0.276]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.007']} position={[-0.003, 0.103, 0.017]} rotation={[-Math.PI, 0.413, -Math.PI]} scale={[-0.884, -0.053, -0.884]} />
      <mesh geometry={nodes.Arbusto1.geometry} material={materials.Arbol_Color1} position={[0.001, 0.156, -0.743]} rotation={[0, 1.569, 0]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1001.geometry} material={materials.Arbol_Color1} position={[-0.536, 0.156, -0.534]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1002.geometry} material={materials.Arbol_Color1} position={[-0.765, 0.156, -0.001]} rotation={[-Math.PI, 0.018, -Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1003.geometry} material={materials.Arbol_Color1} position={[-0.542, 0.156, 0.552]} rotation={[Math.PI, -0.772, Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1004.geometry} material={materials.Arbol_Color1} position={[0.748, 0.156, 0.026]} rotation={[-Math.PI, 0.018, -Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1005.geometry} material={materials.Arbol_Color1} position={[-0.002, 0.156, 0.769]} rotation={[0, 1.569, 0]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1006.geometry} material={materials.Arbol_Color1} position={[0.524, 0.156, 0.557]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Arbusto1007.geometry} material={materials.Arbol_Color1} position={[0.537, 0.156, -0.511]} rotation={[Math.PI, -0.772, Math.PI]} scale={[0.028, 0.028, 0.294]} />
      <mesh geometry={nodes.Torus003.geometry} material={materials['Material.007']} position={[0.028, -0.186, 0.023]} rotation={[0, -0.037, 0]} scale={1.336} />
      <mesh geometry={nodes.Tronco2.geometry} material={materials.Madera_color_2} position={[0.056, 0.883, -0.196]} rotation={[-0.048, 0.407, -0.035]} scale={0.013} />
      <mesh geometry={nodes.Tronco2001.geometry} material={materials.Madera_color_2} position={[0.026, 0.751, 0.2]} rotation={[-0.199, 1.346, 0.14]} scale={0.013} />
      <mesh geometry={nodes.Copa_arbol23.geometry} material={materials.Arbol_Color2} position={[0.073, 0.98, -0.164]} rotation={[0.584, 0.305, -0.273]} scale={0.11} />
      <mesh geometry={nodes.Copa_arbol2001.geometry} material={materials.Arbol_Color2} position={[0.062, 0.848, 0.206]} rotation={[1.167, 0.962, -1.168]} scale={0.11} />
      <mesh geometry={nodes.Copa_arbol22.geometry} material={materials.Arbol_Color2} position={[0.064, 1.004, -0.195]} rotation={[0.584, 0.305, -0.273]} scale={0.076} />
      <mesh geometry={nodes.Copa_arbol2004.geometry} material={materials.Arbol_Color2} position={[0.032, 0.871, 0.195]} rotation={[1.167, 0.962, -1.168]} scale={0.076} />
      <mesh geometry={nodes.Copa_arbol2.geometry} material={materials.Arbol_Color2} position={[0.12, 0.878, -0.047]} rotation={[-0.048, 0.407, -0.035]} scale={0.148} />
      <mesh geometry={nodes.Copa_arbol2005.geometry} material={materials.Arbol_Color2} position={[0.184, 0.745, 0.236]} rotation={[-0.199, 1.346, 0.14]} scale={0.148} />
      <mesh geometry={nodes.Arbusto2.geometry} material={materials['Arbol_Color2.001']} position={[0.649, 0.127, 0.31]} rotation={[0, -0.362, 0]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2001.geometry} material={materials['Arbol_Color2.001']} position={[0.649, 0.127, -0.245]} rotation={[0, 0.544, 0]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2002.geometry} material={materials['Arbol_Color2.001']} position={[0.28, 0.127, -0.632]} rotation={[0, 1.225, 0]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2003.geometry} material={materials['Arbol_Color2.001']} position={[-0.279, 0.127, -0.632]} rotation={[-Math.PI, 1.09, -Math.PI]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2004.geometry} material={materials['Arbol_Color2.001']} position={[-0.666, 0.127, -0.274]} rotation={[-Math.PI, 0.446, -Math.PI]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2005.geometry} material={materials['Arbol_Color2.001']} position={[-0.674, 0.127, 0.289]} rotation={[Math.PI, -0.443, Math.PI]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2006.geometry} material={materials['Arbol_Color2.001']} position={[0.266, 0.127, 0.665]} rotation={[-Math.PI, 1.164, -Math.PI]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.Arbusto2007.geometry} material={materials['Arbol_Color2.001']} position={[-0.292, 0.127, 0.668]} rotation={[Math.PI, -1.288, Math.PI]} scale={[0.06, 0.08, 0.081]} />
      <mesh geometry={nodes.stone003.geometry} material={materials.Mat_tree} position={[0.057, 0.82, -0.243]} scale={0.088} />
      <mesh geometry={nodes.stone001.geometry} material={materials.Mat_tree} position={[0.089, 0.837, -0.185]} rotation={[0, -1.29, 0]} scale={0.059} />
      <mesh geometry={nodes.stone002.geometry} material={materials.Mat_tree} position={[0.047, 0.851, -0.168]} rotation={[0.497, -1.29, 0]} scale={0.059} />
      <mesh geometry={nodes.stone004.geometry} material={materials.Mat_tree} position={[-0.012, 0.687, 0.172]} rotation={[0, 0.943, 0]} scale={0.088} />
      <mesh geometry={nodes.stone005.geometry} material={materials.Mat_tree} position={[0.055, 0.704, 0.181]} rotation={[0, -0.347, 0]} scale={0.059} />
      <mesh geometry={nodes.stone006.geometry} material={materials.Mat_tree} position={[0.044, 0.719, 0.225]} rotation={[0.143, -0.376, -0.428]} scale={0.059} />
    </group>
            </RigidBody>
    
  )
}

export default Base;
useGLTF.preload('/models/base.glb')
