/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/base.glb -o src/components/Base.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Base({ shouldRotate = false, ...props }) {
  const { nodes, materials } = useGLTF("/models/base.glb");
  const rotatingGroupRef = useRef(); // Referencia para el grupo rotante
  const rotatingWaterRef = useRef(); // Referencia para el grupo rotante

  // Rotar solo si shouldRotate es true
  useFrame(() => {
    if (shouldRotate && rotatingGroupRef.current) {
      
      // Crear un vector que representa el eje Y local
      const localYAxis = new THREE.Vector3(0, 1, 0);

      // Rotar alrededor del eje Y local
      rotatingGroupRef.current.rotateOnAxis(localYAxis, 0.002);
    }
    if(rotatingWaterRef.current){
      rotatingWaterRef.current.rotation.y += 0.003; // Velocidad de rotación
    }
  });

  return (
    <group ref={rotatingGroupRef} {...props} dispose={null}>
      <RigidBody type="fixed" name="ground" colliders="trimesh">
        <mesh geometry={nodes.Cube.geometry} material={materials.BRONCE} position={[0, -0.063, 18.422]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.BRONCE} position={[0, -0.038, -18.401]} rotation={[-Math.PI, 0.014, -Math.PI]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.BRONCE} position={[-18.478, -0.063, -0.238]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials.BRONCE} position={[18.486, -0.132, -0.663]} rotation={[-Math.PI, 1.551, -Math.PI]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.BRONCE} position={[13.56, -0.063, 12.675]} rotation={[0, 0.81, 0]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials.BRONCE} position={[-13.295, -0.063, -12.913]} rotation={[Math.PI, -0.806, Math.PI]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials.BRONCE} position={[13.536, -0.063, -12.517]} rotation={[-Math.PI, 0.834, -Math.PI]} />
        <mesh geometry={nodes.Cylinder001.geometry} ref={rotatingWaterRef} material={materials["material agua"]} position={[0, -1.452, 0]} scale={[1.01, 2.012, 1.01]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.BRONCE} position={[-13.049, -0.063, 13.108]} rotation={[0, -0.776, 0]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials["Material.001"]} position={[0, -9.461, 0]} scale={[1, 3.991, 1]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials.BRONCE} position={[4.036, -6.989, 13.642]} rotation={[0, 0.283, 0]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials.BRONCE} position={[-3.818, -6.945, -13.642]} rotation={[Math.PI, -0.268, Math.PI]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube010.geometry} material={materials.BRONCE} position={[-13.673, -6.989, 3.853]} rotation={[0, -1.288, 0]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials.BRONCE} position={[13.612, -7.114, -4.398]} rotation={[-Math.PI, 1.269, -Math.PI]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube012.geometry} material={materials.BRONCE} position={[12.808, -6.989, 6.49]} rotation={[0, 1.093, 0]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube013.geometry} material={materials.BRONCE} position={[-12.576, -6.989, -6.691]} rotation={[Math.PI, -1.089, Math.PI]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube014.geometry} material={materials.BRONCE} position={[7.419, -6.989, -12.146]} rotation={[-Math.PI, 0.551, -Math.PI]} scale={[0.501, 1.789, 0.771]} />
        <mesh geometry={nodes.Cube015.geometry} material={materials.BRONCE} position={[-6.756, -6.989, 12.542]} rotation={[0, -0.493, 0]} scale={[0.501, 1.789, 0.771]} />
        <group position={[0.04, -19.669, 0.03]} rotation={[0, 0.413, 0]} scale={[0.84, 3.352, 0.84]}>
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials["Material.001"]} />
          <mesh geometry={nodes.Cylinder002_2.geometry} material={materials["Material.006"]} />
        </group>
        <mesh geometry={nodes.Cube016.geometry} material={materials.BRONCE} position={[7.741, -17.592, 9.167]} rotation={[0, 0.696, 0]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube017.geometry} material={materials.BRONCE} position={[-7.494, -17.555, -9.179]} rotation={[Math.PI, -0.681, Math.PI]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials.BRONCE} position={[-9.182, -17.592, 7.601]} rotation={[0, -0.875, 0]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube019.geometry} material={materials.BRONCE} position={[9.032, -17.697, -7.939]} rotation={[-Math.PI, 0.856, -Math.PI]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube020.geometry} material={materials.BRONCE} position={[12.081, -17.592, 0.709]} rotation={[0, 1.505, 0]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube021.geometry} material={materials.BRONCE} position={[-11.89, -17.592, -0.881]} rotation={[Math.PI, -1.502, Math.PI]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube022.geometry} material={materials.BRONCE} position={[1.656, -17.592, -11.814]} rotation={[-Math.PI, 0.138, -Math.PI]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cube023.geometry} material={materials.BRONCE} position={[-0.932, -17.592, 11.956]} rotation={[0, -0.08, 0]} scale={[0.421, 1.502, 0.648]} />
        <mesh geometry={nodes.Cylinder004.geometry} material={materials["material agua"]} position={[0, -9.674, 0]} scale={[0.684, 3.072, 0.684]} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials["material agua"]} position={[0, -20.013, 0]} scale={[0.617, 2.771, 0.617]} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials["Material.001"]} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials["Material.002"]} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials["Material.003"]} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.Material} />
      </RigidBody>
    </group>
  );
}
export default Base;

useGLTF.preload("/models/base.glb");
