/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/google_calendar.glb -o src/components/GoogleCalendar.jsx -r public 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'

export const GoogleCalendar = React.memo(({
  handleClick,
  canInteract,
  isInteracting,
  setIsInteracting,
  position,
  rotation,
  scale,
  ...props
}) => {
  const { nodes, materials } = useGLTF('/models/google_calendar.glb')
  const [hoverMessage, setHoverMessage] = useState(null)
  const [clickCooldown, setClickCooldown] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const isHovering = useRef(false)
  
  const handlePhoneClick = () => {
    if (clickCooldown || !canInteract || isInteracting) return

    handleClick("schedule_meeting")
    // setIsInteracting(true); // La línea original está comentada

    const cooldownTime = 2 * 60 // Cooldown en segundos
    setClickCooldown(true)
    setCountdown(cooldownTime)

    const interval = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) {
          clearInterval(interval)
          setClickCooldown(false)
          setIsInteracting(false)
          return 0
        }
        return prev - 1
      })
    }, 1000)
  }

  const setMaterialsEmissive = (color, intensity) => {
    Object.values(materials).forEach((material) => {
      material.emissive.set(color)
      material.emissiveIntensity = intensity
    })
  }

  const handlePointerOver = () => {
    if (canInteract && !isInteracting) {
      isHovering.current = true
      setMaterialsEmissive("yellow", 0.1)
      document.body.style.cursor = "pointer"
      setHoverMessage(clickCooldown ? `Espera ${countdown}s` : "Agendar reunión")
    }
  }

  const handlePointerOut = () => {
    isHovering.current = false
    setMaterialsEmissive("black", 0)
    document.body.style.cursor = "default"
    setHoverMessage(null)
  }

  useEffect(() => {
    if (!isHovering.current) setHoverMessage(null)

    if (clickCooldown) {
      setHoverMessage(`Espera ${countdown}s`)
    } else if (isHovering.current && canInteract && !isInteracting) {
      setHoverMessage("Interactuar con el teléfono")
    }
  }, [clickCooldown, countdown, canInteract, isInteracting])

  return (
    <>
      <group
        {...props}
        dispose={null}
        position={position}
        rotation={rotation}
        scale={scale}
        onClick={handlePhoneClick}
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
      >
        <group position={[0, -0.002, 0]} scale={[0.128, 0.973, 0.973]}>
          <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cube001_4.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cube001_5.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube001_6.geometry} material={materials['Material.009']} />
        </group>
        <mesh
          geometry={nodes.Text.geometry}
          material={materials['Material.004']}
          position={[0.11, -0.255, 0.343]}
          rotation={[1.571, 0.028, -1.573]}
          scale={1.041}
        />
      </group>

      {/* Mensaje interactivo */}
      {hoverMessage && isHovering.current && canInteract && !isInteracting && (
        <Html position={[position[0], position[1] + 0.4, position[2]]} distanceFactor={3}>
          <div
            style={{
              background: "rgba(0, 0, 0, 0.75)",
              color: "white",
              padding: "5px 10px",
              borderRadius: "5px",
              fontSize: "18px",
              textAlign: "center",
              whiteSpace: "nowrap",
            }}
          >
            {hoverMessage}
          </div>
        </Html>
      )}
    </>
  )
})

export default GoogleCalendar
useGLTF.preload('/models/google_calendar.glb')
