/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/google_calendar.glb -o src/components/GoogleCalendar.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GoogleCalendar(props) {
  const { nodes, materials } = useGLTF('/models/google_calendar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]} scale={[0.128, 0.973, 0.973]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.004']} position={[0.11, -0.255, 0.343]} rotation={[1.571, 0.028, -1.573]} scale={1.041} />
    </group>
  )
}


export default GoogleCalendar;
useGLTF.preload('/models/google_calendar.glb')
