/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lobby.glb -o src/components/Lobby.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Lobby(props) {
  const { nodes, materials } = useGLTF('/models/lobby.glb')
  return (
    <RigidBody type="fixed" name="ground" colliders="trimesh">
      <group {...props} dispose={null}>
        <group position={[-0.016, -0.126, 0.003]} scale={[26.852, 1.908, 3.927]}>
          <mesh
            geometry={nodes.Plane_1.geometry}
            material={materials['Material.001']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane_2.geometry}
            material={materials['Material.001']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane_3.geometry}
            material={materials['Material.004']}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          geometry={nodes.colummna001.geometry}
          material={materials['Material.016']}
          position={[26.734, 5.114, 9.036]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna002.geometry}
          material={materials['Material.016']}
          position={[11.749, 5.114, 9.036]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials['Material.016']}
          position={[4.314, 5.114, 8.974]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials['Material.016']}
          position={[-3.149, 5.114, 8.974]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials['Material.016']}
          position={[-18.041, 5.114, 8.986]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials['Material.016']}
          position={[-18.041, 5.114, -3.804]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials['Material.016']}
          position={[-3.046, 5.114, -3.76]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials['Material.016']}
          position={[4.431, 5.114, -3.76]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna.geometry}
          material={materials['Material.016']}
          position={[11.993, 5.114, -3.76]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials['Material.016']}
          position={[26.84, 5.114, -3.91]}
          rotation={[Math.PI, -0.777, Math.PI]}
          scale={[-1.829, -5.249, -1.829]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna003.geometry}
          material={materials['Material.012']}
          position={[26.694, -0.054, 9.046]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna004.geometry}
          material={materials['Material.012']}
          position={[11.74, -0.054, 8.983]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna005.geometry}
          material={materials['Material.012']}
          position={[4.304, -0.054, 8.983]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna006.geometry}
          material={materials['Material.012']}
          position={[-3.158, -0.054, 8.983]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna007.geometry}
          material={materials['Material.012']}
          position={[-18.011, -0.062, 8.943]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna008.geometry}
          material={materials['Material.012']}
          position={[-17.987, -0.054, -3.807]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna009.geometry}
          material={materials['Material.012']}
          position={[-3.127, -0.054, -3.807]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna010.geometry}
          material={materials['Material.012']}
          position={[4.421, -0.054, -3.807]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna011.geometry}
          material={materials['Material.012']}
          position={[12.029, -0.054, -3.807]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.colummna012.geometry}
          material={materials['Material.012']}
          position={[26.812, -0.054, -3.957]}
          rotation={[0, 0.777, 0]}
          scale={[2.616, 0.141, 2.616]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials['Material.018']}
          position={[4.469, -0.109, 2.642]}
          scale={[22.312, 1, 6.373]}
          castShadow
          receiveShadow
        />
        <group position={[4.537, -0.086, 2.659]} scale={[22.46, 1, 1.948]}>
          <mesh
            geometry={nodes.Plane003_1.geometry}
            material={materials['Material.019']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane003_2.geometry}
            material={materials['Material.020']}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials['Material.021']}
          position={[19.553, 0.204, -3.239]}
          rotation={[1.575, -Math.PI / 2, 0]}
          scale={[0.311, 0.311, 0.533]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials['Material.021']}
          position={[19.218, 0.204, 8.494]}
          rotation={[-1.575, Math.PI / 2, 0]}
          scale={[0.311, 0.311, 0.533]}
          castShadow
          receiveShadow
        />
        <group position={[17.056, 0.74, -3.031]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[17.056, 0.74, 8.23]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[21.583, 0.74, 8.23]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[21.806, 0.74, -3.031]} rotation={[0, -1.048, 0]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-7.699, 0.74, 8.23]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-13.698, 0.74, 8.23]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-7.699, 0.74, -3.169]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-13.698, 0.74, -3.169]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials['color_Palette.010']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials['Material.006']}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          geometry={nodes.cuadros.geometry}
          material={nodes.cuadros.material}
          position={[19.295, 1.583, -3.756]}
          rotation={[Math.PI, 1.571, 0]}
          scale={[0.043, 1.142, 2.227]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.cuadros001.geometry}
          material={nodes.cuadros001.material}
          position={[19.295, 1.583, 8.959]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.043, 1.142, 2.227]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.cuadros002.geometry}
          material={nodes.cuadros002.material}
          position={[-10.719, 1.583, 8.959]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={[0.043, 1.142, 2.227]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.cuadros003.geometry}
          material={nodes.cuadros003.material}
          position={[-10.638, 1.583, -3.756]}
          rotation={[Math.PI, 1.571, 0]}
          scale={[0.043, 1.142, 2.227]}
          castShadow
          receiveShadow
        />
        <group position={[12.857, 0.063, -1.224]} rotation={[-Math.PI, 0.809, -2.516]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[14.729, 0.063, -3.008]} rotation={[-Math.PI, 0.809, -2.516]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[11.289, 0.067, -1.064]} rotation={[0.06, 0.761, 0.424]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[11.289, 0.067, -1.064]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[9.244, 0.062, -3.192]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[7.208, 0.062, -3.192]} rotation={[3.129, 0.792, -2.668]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[5.166, 0.086, -1.178]} rotation={[3.129, 0.792, -2.668]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[3.774, 0.072, -0.946]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[1.695, 0.098, -3.202]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-0.363, 0.107, -3.172]} rotation={[3.128, 0.861, -2.666]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-2.585, 0.098, -0.928]} rotation={[3.128, 0.861, -2.666]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-3.752, 0.098, -0.928]} rotation={[0.012, 0.785, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-5.786, 0.123, -2.964]} rotation={[0.012, 0.785, 0.457]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-3.936, 0.063, 6.473]} rotation={[0, -0.818, 0.626]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-5.824, 0.063, 8.24]} rotation={[0, -0.818, 0.626]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-2.367, 0.067, 6.327]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-0.341, 0.062, 8.474]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[1.568, 0.107, 8.361]} rotation={[0.012, -0.801, 0.474]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[3.576, 0.095, 6.312]} rotation={[0.012, -0.801, 0.474]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[5.111, 0.097, 6.311]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[7.003, 0.096, 8.326]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[9.06, 0.107, 8.311]} rotation={[0.013, -0.87, 0.475]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[11.267, 0.098, 6.116]} rotation={[0.013, -0.87, 0.475]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[12.524, 0.096, 6.174]} rotation={[3.13, -0.776, -2.685]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[14.498, 0.121, 8.185]} rotation={[3.13, -0.776, -2.685]} scale={[0.04, 0.189, 0.189]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          geometry={nodes.Plane013.geometry}
          material={materials.vidrio}
          position={[26.924, 1.404, 3.408]}
          rotation={[0, 0, 1.573]}
          scale={[1.707, 1, 0.823]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials.vidrio}
          position={[26.924, 1.404, 1.76]}
          rotation={[0, 0, 1.573]}
          scale={[1.707, 1, 0.823]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[26.924, 0.296, 2.694]}
          scale={0.028}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[26.924, 0.296, 2.483]}
          scale={0.028}
          castShadow
          receiveShadow
        />
        <group position={[18.791, 0.354, 5.349]} rotation={[0, -0.853, 0]} scale={[0.336, 0.171, 0.013]}>
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials['Material.005']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials['Material.007']}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-12.882, 0.358, 0.063]} rotation={[Math.PI, -1.235, Math.PI]} scale={[0.346, 0.176, 0.013]}>
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials['Material.005']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials['Material.007']}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          geometry={nodes.Text.geometry}
          material={materials['Material.012']}
          position={[18.838, 0.42, 5.312]}
          rotation={[1.555, 0, -2.265]}
          scale={0.098}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[-12.831, 0.426, 0.086]}
          rotation={[1.59, 0, -1.222]}
          scale={0.088}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials['Material.009']}
          position={[-16.633, 0.08, 2.682]}
          scale={[1.342, 0.23, 2.36]}
          castShadow
          receiveShadow
        />
        <group position={[-17.23, 0.602, 4.761]} scale={0.283}>
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials.material_ggris_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials.morado_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube011_3.geometry}
            material={materials.beige_est}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-17.153, 0.645, 0.635]} scale={0.283}>
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials.material_ggris_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials.morado_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube011_3.geometry}
            material={materials.beige_est}
            castShadow
            receiveShadow
          />
        </group>
        <group position={[-17.34, 1.709, 2.701]} scale={[0.396, 1.345, 1.602]}>
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials.material_ggris_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials.morado_est}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Cube012_3.geometry}
            material={materials.beige_est}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </RigidBody>
  )
}

export default Lobby
useGLTF.preload('/models/lobby.glb')
