/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lobby.glb -o src/components/Lobby2.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/lobby.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.016, -0.126, 0.003]} scale={[26.852, 1.908, 3.927]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.colummna001.geometry} material={materials['Material.016']} position={[26.734, 5.114, 9.036]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.colummna002.geometry} material={materials['Material.016']} position={[11.749, 5.114, 9.036]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.016']} position={[4.314, 5.114, 8.974]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.016']} position={[-3.149, 5.114, 8.974]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.016']} position={[-18.041, 5.114, 8.986]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.016']} position={[-18.041, 5.114, -3.804]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.016']} position={[-3.046, 5.114, -3.76]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.016']} position={[4.431, 5.114, -3.76]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.colummna.geometry} material={materials['Material.016']} position={[11.993, 5.114, -3.76]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.016']} position={[26.84, 5.114, -3.91]} rotation={[Math.PI, -0.777, Math.PI]} scale={[-1.829, -5.249, -1.829]} />
      <mesh geometry={nodes.colummna003.geometry} material={materials['Material.012']} position={[26.694, -0.054, 9.046]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna004.geometry} material={materials['Material.012']} position={[11.74, -0.054, 8.983]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna005.geometry} material={materials['Material.012']} position={[4.304, -0.054, 8.983]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna006.geometry} material={materials['Material.012']} position={[-3.158, -0.054, 8.983]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna007.geometry} material={materials['Material.012']} position={[-18.011, -0.062, 8.943]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna008.geometry} material={materials['Material.012']} position={[-17.987, -0.054, -3.807]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna009.geometry} material={materials['Material.012']} position={[-3.127, -0.054, -3.807]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna010.geometry} material={materials['Material.012']} position={[4.421, -0.054, -3.807]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna011.geometry} material={materials['Material.012']} position={[12.029, -0.054, -3.807]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.colummna012.geometry} material={materials['Material.012']} position={[26.812, -0.054, -3.957]} rotation={[0, 0.777, 0]} scale={[2.616, 0.141, 2.616]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.018']} position={[4.469, -0.109, 2.642]} scale={[22.312, 1, 6.373]} />
      <group position={[4.537, -0.086, 2.659]} scale={[22.064, 1, 1.948]}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.021']} position={[19.553, 0.204, -3.239]} rotation={[1.575, -Math.PI / 2, 0]} scale={[0.311, 0.311, 0.533]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.021']} position={[19.218, 0.204, 8.494]} rotation={[-1.575, Math.PI / 2, 0]} scale={[0.311, 0.311, 0.533]} />
      <group position={[17.056, 0.74, -3.031]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[17.056, 0.74, 8.23]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[21.583, 0.74, 8.23]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[21.806, 0.74, -3.031]} rotation={[0, -1.048, 0]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-7.699, 0.74, 8.23]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-13.698, 0.74, 8.23]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-7.699, 0.74, -3.169]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-13.698, 0.74, -3.169]} rotation={[Math.PI, -0.836, Math.PI]} scale={0.168}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['color_Palette.010']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[12.857, 0.063, -1.224]} rotation={[-Math.PI, 0.809, -2.516]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[14.729, 0.063, -3.008]} rotation={[-Math.PI, 0.809, -2.516]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[11.289, 0.067, -1.064]} rotation={[0.06, 0.761, 0.424]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[11.289, 0.067, -1.064]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[9.244, 0.062, -3.192]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[7.208, 0.062, -3.192]} rotation={[3.129, 0.792, -2.668]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[5.166, 0.086, -1.178]} rotation={[3.129, 0.792, -2.668]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[3.774, 0.072, -0.946]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[1.695, 0.098, -3.202]} rotation={[0.012, 0.745, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.363, 0.107, -3.172]} rotation={[3.128, 0.861, -2.666]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-2.585, 0.098, -0.928]} rotation={[3.128, 0.861, -2.666]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-3.752, 0.098, -0.928]} rotation={[0.012, 0.785, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-5.786, 0.123, -2.964]} rotation={[0.012, 0.785, 0.457]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-3.936, 0.063, 6.473]} rotation={[0, -0.818, 0.626]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-5.824, 0.063, 8.24]} rotation={[0, -0.818, 0.626]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-2.367, 0.067, 6.327]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.341, 0.062, 8.474]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[1.568, 0.107, 8.361]} rotation={[0.012, -0.801, 0.474]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[3.576, 0.095, 6.312]} rotation={[0.012, -0.801, 0.474]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[5.111, 0.097, 6.311]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[7.003, 0.096, 8.326]} rotation={[3.13, -0.736, -2.684]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[9.06, 0.107, 8.311]} rotation={[0.013, -0.87, 0.475]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[11.267, 0.098, 6.116]} rotation={[0.013, -0.87, 0.475]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[12.524, 0.096, 6.174]} rotation={[3.13, -0.776, -2.685]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[14.498, 0.121, 8.185]} rotation={[3.13, -0.776, -2.685]} scale={[0.04, 0.189, 0.189]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Plane013.geometry} material={materials.vidrio} position={[26.924, 0.721, 3.094]} rotation={[0, 0, 1.573]} scale={[0.887, 0.576, 0.51]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.vidrio} position={[26.924, 0.721, 2.074]} rotation={[0, 0, 1.573]} scale={[0.887, 0.576, 0.51]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[26.924, 0.296, 2.694]} scale={0.028} />
      <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[26.924, 0.296, 2.483]} scale={0.028} />
      <group position={[18.791, 0.354, 5.349]} rotation={[0, -0.853, 0]} scale={[0.336, 0.171, 0.013]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-12.882, 0.358, 0.063]} rotation={[Math.PI, -1.235, Math.PI]} scale={[0.346, 0.176, 0.013]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.012']} position={[18.838, 0.42, 5.312]} rotation={[Math.PI / 2, 0, -2.269]} scale={0.098} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[-12.831, 0.426, 0.086]} rotation={[Math.PI / 2, 0, -1.222]} scale={0.088} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.009']} position={[-16.633, 0.08, 2.682]} scale={[1.342, 0.23, 2.36]} />
      <group position={[-17.23, 0.602, 4.761]} scale={0.283}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.material_ggris_est} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.morado_est} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials.beige_est} />
      </group>
      <group position={[-17.153, 0.645, 0.635]} scale={0.283}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.material_ggris_est} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.morado_est} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials.beige_est} />
      </group>
      <group position={[-17.34, 1.709, 2.701]} scale={[0.396, 1.345, 1.602]}>
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.material_ggris_est} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials.morado_est} />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials.beige_est} />
      </group>
      <group position={[-16.671, 1.515, -2.535]} rotation={[Math.PI, 0.79, 0]} scale={[0.03, 0.783, 0.757]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.015']} />
      </group>
      <group position={[19.406, 1.62, -3.654]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.03, 0.783, 0.757]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.014']} />
      </group>
      <group position={[19.466, 1.62, 8.832]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.03, 0.783, 0.757]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-16.703, 1.602, 7.66]} rotation={[Math.PI, -0.78, 0]} scale={[0.03, 0.783, 0.757]}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.022']} position={[3.494, -0.328, 2.517]} scale={[38.016, 1, 23.271]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.017']} position={[3.494, -0.174, 2.966]} scale={[28.955, 0.762, 12.872]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.017']} position={[3.494, -0.174, 2.966]} scale={[39.97, 1.051, 24.189]} />
      <group position={[3.466, 10.55, -24.871]} scale={[42.529, 11.096, 1]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.024']} />
      </group>
      <group position={[3.466, 10.55, 30.75]} rotation={[Math.PI, 0, Math.PI]} scale={[42.529, 11.096, 1]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.024']} />
      </group>
      <group position={[-40.288, 10.55, 3.122]} rotation={[0, Math.PI / 2, 0]} scale={[28.805, 11.096, 1]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.024']} />
      </group>
      <group position={[47.456, 10.55, 3.122]} rotation={[0, -Math.PI / 2, 0]} scale={[28.2, 11.096, 1]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.024']} />
      </group>
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.010']} position={[12.98, 1.853, 7.676]} rotation={[1.56, 0.021, -2.349]} scale={0.187} />
      <group position={[5.776, 1.295, -2.48]} rotation={[Math.PI, 0.781, 0]} scale={[0.03, 0.783, 1.307]}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.026']} />
      </group>
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.010']} position={[13.367, 1.95, -2.492]} rotation={[1.561, 0.021, -0.76]} scale={0.187} />
      <group position={[-1.778, 1.317, 7.641]} rotation={[Math.PI, -0.788, 0]} scale={[0.03, 0.783, 1.307]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.027']} />
      </group>
      <group position={[5.83, 1.295, 7.58]} rotation={[Math.PI, -0.781, 0]} scale={[0.03, 0.783, 1.307]}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['Material.028']} />
      </group>
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.010']} position={[-10.798, 1.411, 8.931]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.187} />
      <group position={[-1.721, 1.317, -2.448]} rotation={[Math.PI, 0.788, 0]} scale={[0.03, 0.783, 1.307]}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials['Material.029']} />
      </group>
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.010']} position={[-10.855, 0.877, -3.753]} rotation={[Math.PI / 2, 0, 0]} scale={0.187} />
      <group position={[-10.824, -0.005, 8.65]} rotation={[0, 0, -Math.PI]} scale={[-1.854, -0.38, -1.151]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.031']} />
      </group>
      <group position={[-10.824, -0.005, -3.728]} rotation={[-Math.PI, 0, 0]} scale={[-1.854, -0.38, -1.151]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.031']} />
      </group>
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.032']} position={[-10.787, 0.273, 8.505]} scale={[1.674, 1, 1]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.032']} position={[-10.787, 0.273, -3.823]} scale={[1.674, 1, 1]} />
      <group position={[-17.927, 5.793, 2.657]} rotation={[0, 0, -Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[-16.659, 5.793, -2.542]} rotation={[0, -0.801, -Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[-16.757, 5.793, 7.656]} rotation={[0, 0.782, -Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[-4.515, 5.793, 7.724]} rotation={[-Math.PI, 0.805, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[2.921, 5.793, 7.724]} rotation={[-Math.PI, 0.805, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[10.405, 5.793, 7.724]} rotation={[-Math.PI, 0.805, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[10.672, 5.793, -2.4]} rotation={[Math.PI, -0.781, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[3.159, 5.793, -2.4]} rotation={[Math.PI, -0.781, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
      <group position={[-4.378, 5.793, -2.4]} rotation={[Math.PI, -0.781, Math.PI / 2]} scale={[4.184, 1, 0.856]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.033']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/lobby.glb')
