/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/screen.glb -o src/components/Screen.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Screen(props) {
  const { nodes, materials } = useGLTF('/models/screen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PANTALLA_GRANDE.geometry} material={nodes.PANTALLA_GRANDE.material} position={[0, 8.19, 0.052]} scale={[0.118, 3.645, 2.093]} />
    </group>
  )
}

export default Screen;
useGLTF.preload('/models/screen.glb')
