/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_silver.glb -o src/components/StandSilver.jsx -r public 
*/

import React, { memo } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export const StandSilver = memo((props) => {
  const { nodes, materials } = useGLTF('/models/stand_silver.glb')
  return (
    <RigidBody type="fixed" name="ground" colliders="trimesh">
      <group {...props} dispose={null}>
        <group position={[-1.442, 1.741, 1.894]} scale={[0.328, 1.537, 0.118]}>
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.SILVER} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.NEGRO} />
        </group>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.SILVER}
          position={[0.554, 1.5, -1.997]}
          scale={[1.887, 1.307, 0.065]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.NEGRO}
          position={[2.377, 2.742, -1.061]}
          scale={[0.058, 0.057, 0.889]}
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials.NEGRO}
          position={[2.375, 1.487, -0.116]}
          scale={[0.06, 1.314, 0.063]}
        />
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials.NEGRO}
          position={[0.543, 2.734, -0.116]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.068, 1.736, 0.065]}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials.SILVER}
          position={[0.554, 0.852, -1.773]}
          scale={[1.19, 0.029, 0.172]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.NEGRO}
          position={[1.778, 0.703, -1.764]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.037, -0.533, -0.164]}
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials.NEGRO}
          position={[-0.668, 0.703, -1.764]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.037, -0.533, -0.164]}
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials.SILVER}
          position={[1.81, 0.805, 1.775]}
          scale={[0.542, 0.026, 0.199]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials.NEGRO}
          position={[2.368, 0.67, 1.775]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.017, -0.48, -0.2]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.NEGRO}
          position={[1.253, 0.67, 1.775]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.017, -0.48, -0.2]}
        />
        <group position={[1.812, 0.514, 1.985]} scale={[0.572, 0.317, 0.016]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials.SILVER} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.SILVER} />
        </group>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.SILVER}
          position={[0.535, 2.865, -1.06]}
          scale={[1.876, 0.062, 1.015]}
        />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials['Material.003']}
          position={[3.186, 3.93, -1.995]}
          rotation={[3.142, -1.564, Math.PI / 2]}
          scale={[0.718, 0.718, 0.463]}
        />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials.negro_soporte}
          position={[2.684, 0.281, -2.001]}
          rotation={[Math.PI, -1.564, Math.PI]}
          scale={0.058}
        />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
          position={[0.448, 0.192, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-2.89, -0.017, -2.89]}
        />
      </group>
    </RigidBody>
  )
})

export default StandSilver

useGLTF.preload('/models/stand_silver.glb')
