/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Stand3.glb -o src/components/StandVip.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StandVip(props) {
  const { nodes, materials } = useGLTF('/models/Stand3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Stand3.geometry} material={nodes.Base_Stand3.material} position={[-0.564, 0.21, -0.003]} scale={[0.02, 0.167, 0.263]} />
    </group>
  )
}

export default StandVip;
useGLTF.preload('/models/Stand3.glb')
