/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_bronce.glb -o src/components/StandBronce.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier';

export function StandBronce(props) {
  const { nodes, materials } = useGLTF('/models/stand_bronce.glb')
  return (
    <RigidBody type="fixed" name="ground" colliders="trimesh">
    
    <group {...props} dispose={null} castShadow receiveShadow>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 0.143, 0]} scale={[1, 0.096, 1]} />
      <group position={[0, 7.778, 0]} scale={[3.056, 7.666, 3.056]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.negro} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.bronce} />
      </group>
      <group position={[0.045, 8.219, 2.528]} scale={[1.687, 2.745, 0.422]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.negro} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.bronce} />
      </group>
    </group>
    </RigidBody>
  )
}

export default StandBronce;
useGLTF.preload('/models/stand_bronce.glb')
