/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/StandPremium.glb -o src/components/StandPremium.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StandPremium(props) {
  const { nodes, materials } = useGLTF('/models/StandPremium.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Stand2.geometry} material={nodes.Base_Stand2.material} scale={0.197} />
      <mesh geometry={nodes.TV2.geometry} material={nodes.TV2.material} position={[-0.092, -0.1, 0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
      <mesh geometry={nodes.TV3.geometry} material={nodes.TV3.material} position={[-0.092, -0.1, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
      <mesh geometry={nodes.TV4.geometry} material={nodes.TV4.material} position={[-0.092, -0.1, -0.13]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
    </group>
  )
}

export default StandPremium;
useGLTF.preload('/models/StandPremium.glb')
