/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_bronce.glb -o src/components/StandBronce.jsx -r public 
*/

import React, { memo } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export const StandBronce = memo((props) => {
  const { nodes, materials } = useGLTF('/models/stand_bronce.glb')
  console.log("StandBronce renderizado");

  return (
    <RigidBody type="fixed" name="ground" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[0.064, 0, 0]}
          scale={[1.051, 0.018, 1.299]}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials['Material.001']}
          position={[-0.879, 1.025, 0]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.021, -0.727, -1.15]}
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.negro_soporte}
          position={[0.246, 0.044, 1.114]}
          scale={0.031}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.negro_soporte}
          position={[0.246, 0.044, -1.107]}
          scale={0.031}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials.negro_soporte}
          position={[0.236, 1.27, -1.108]}
          rotation={[0, 0, 0.797]}
          scale={-0.029}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.negro_soporte}
          position={[0.236, 1.271, 1.114]}
          rotation={[0, 0, 0.797]}
          scale={-0.029}
        />
        <group position={[0, 0.295, 0.576]} scale={[0.209, 0.01, 0.315]}>
          <mesh
            geometry={nodes.Cube004_1.geometry}
            material={materials['Material.002']}
          />
          <mesh
            geometry={nodes.Cube004_2.geometry}
            material={materials['Material.001']}
          />
        </group>
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials.negro_soporte}
          position={[-0.932, 0.013, -1.215]}
          scale={0.023}
        />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials['Material.001']}
          position={[-0.931, 1.451, -1.411]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.28, 0.28, 0.181]}
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials.negro_soporte}
          position={[0, 1.504, 0]}
          rotation={[0, 0, 0.785]}
          scale={[-0.027, -0.027, -1.088]}
        />
      </group>
    </RigidBody>
  )
})

export default StandBronce

useGLTF.preload('/models/stand_bronce.glb')
