/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_gold.glb -o src/components/StandGold.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StandGold(props) {
  const { nodes, materials } = useGLTF('/models/stand_gold.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.889, 0.348, 0]} scale={[0.07, 0.385, 1.104]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-0.956, 0.412, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, -0.439, -0.621]} />
      <group position={[0.653, 0.312, 1.04]} scale={[0.247, 0.34, 0.174]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.653, 0.312, -0.98]} scale={[0.247, 0.34, 0.174]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.432, 0.095, 0.343]} scale={0.124}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.432, 0.095, -0.328]} scale={0.124}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.173, -0.029, -0.013]} scale={[1.758, 0.009, 1.758]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.005']} position={[-0.931, 1.451, -1.651]} rotation={[0, 0, -Math.PI / 2]} scale={[0.28, 0.28, 0.181]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.negro_soporte} position={[-0.932, 0.013, -1.456]} scale={0.023} />
    </group>
  )
}


export default StandGold;
useGLTF.preload('/models/stand_gold.glb')
