/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Stand2.glb -o src/components/StandPremium.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StandPremium(props) {
  const { nodes, materials } = useGLTF('/models/Stand2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Stand2.geometry} material={nodes.Base_Stand2.material} position={[-1.152, 0.333, 0.018]} scale={0.197} />
      <mesh geometry={nodes.TV2.geometry} material={nodes.TV2.material} position={[-1.241, 0.266, 0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
      <mesh geometry={nodes.TV3.geometry} material={nodes.TV3.material} position={[-1.241, 0.266, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
      <mesh geometry={nodes.TV4.geometry} material={nodes.TV4.material} position={[-1.241, 0.266, -0.11]} rotation={[-Math.PI / 2, 0, 0]} scale={0.139} />
    </group>
  )
}

export default StandPremium;
useGLTF.preload('/models/Stand2.glb')
