/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_gold.glb -o src/components/StandGold.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function StandGold(props) {
  const { nodes, materials } = useGLTF('/models/stand_gold.glb')
  return (
        <RigidBody type="fixed" name="ground" colliders="trimesh">
    
    <group {...props} dispose={null}>
      <group position={[-0.889, 0.348, 0]} scale={[0.07, 0.385, 1.104]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-0.956, 0.412, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, -0.439, -0.621]} />
      <group position={[0.773, 0.095, 0.211]} scale={0.124}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.653, 0.312, 1.04]} scale={[0.247, 0.34, 0.174]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.313, -0.015, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.74, -0.014, -0.74]} />
      <group position={[0.653, 0.312, -1.05]} scale={[0.247, 0.34, 0.174]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Material} />
      </group>
      <group position={[0.432, 0.095, 0.617]} scale={0.124}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.773, 0.095, -0.263]} scale={0.124}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.Material} />
      </group>
      <group position={[0.433, 0.095, -0.605]} scale={0.124}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials.Material} />
      </group>
    </group>
        </RigidBody>
    
  )
}

export default StandGold;
useGLTF.preload('/models/stand_gold.glb')
