/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stand_bronce.glb -o src/components/StandBronce.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StandBronce(props) {
  const { nodes, materials } = useGLTF('/models/stand_bronce.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0.064, 0, 0]} scale={[1.051, 0.018, 1.299]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-0.879, 1.025, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.021, -0.727, -1.15]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.negro_soporte} position={[0.246, 0.044, 1.137]} scale={0.031} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.negro_soporte} position={[0.246, 0.044, -1.138]} scale={0.031} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.negro_soporte} position={[0.236, 1.27, -1.139]} rotation={[0, 0, 0.797]} scale={-0.029} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.negro_soporte} position={[0.236, 1.271, 1.137]} rotation={[0, 0, 0.797]} scale={-0.029} />
      <group position={[0, 0.295, 0.576]} scale={[0.209, 0.01, 0.315]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.Cube010.geometry} material={materials.negro_soporte} position={[-0.932, 0.013, -1.215]} scale={0.023} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-0.931, 1.451, -1.411]} rotation={[0, 0, -Math.PI / 2]} scale={[0.28, 0.28, 0.181]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.negro_soporte} position={[0, 1.504, 0]} rotation={[0, 0, 0.785]} scale={[-0.027, -0.027, -1.143]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['negro_soporte.001']} position={[-0.87, 1.342, 1.137]} rotation={[-3.139, -0.021, -2.207]} scale={-0.029} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['negro_soporte.001']} position={[-0.876, 0.003, 1.137]} rotation={[Math.PI, -0.021, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['negro_soporte.001']} position={[-0.886, 0.028, -1.138]} rotation={[Math.PI, -0.021, Math.PI]} scale={0.031} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.negro_soporte} position={[-0.25, 1.807, 0.003]} rotation={[0, 0, 0.653]} scale={[-0.035, -0.035, -1.191]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[0.151, 0.354, 0.836]} scale={0.025} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[0.151, 0.354, 0.327]} scale={0.025} />
      <mesh geometry={nodes.flower1.geometry} material={materials.color_Palette} position={[0.154, 0.401, 0.836]} rotation={[0, -1.287, 0]} scale={0.11} />
      <mesh geometry={nodes.flower1001.geometry} material={materials.color_Palette} position={[0.154, 0.401, 0.328]} rotation={[0, -1.287, 0]} scale={0.11} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.005']} position={[0.153, 0.335, 0.837]} scale={-0.03} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.005']} position={[0.153, 0.335, 0.328]} scale={-0.03} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['negro_soporte.001']} position={[-0.865, 1.34, -1.139]} rotation={[-3.139, -0.021, -2.207]} scale={-0.029} />
    </group>
  )
}

export default StandBronce;
useGLTF.preload('/models/stand_bronce.glb')
