/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TEST.glb -o src/components/Test.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier';

export function Test(props) {
  const { nodes, materials } = useGLTF('/models/TEST.glb')
  return (
          <RigidBody type="fixed" name="ground" colliders="trimesh">
    
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.006']} />
    </group>
    </RigidBody>
  )
}

export default Test;
useGLTF.preload('/models/TEST.glb')
