export const applyAccentRules = (value) => {
    return value
      // Acento agudo (´)
      .replace(/´a/g, 'á')
      .replace(/´e/g, 'é')
      .replace(/´i/g, 'í')
      .replace(/´o/g, 'ó')
      .replace(/´u/g, 'ú')
      .replace(/´A/g, 'Á')
      .replace(/´E/g, 'É')
      .replace(/´I/g, 'Í')
      .replace(/´O/g, 'Ó')
      .replace(/´U/g, 'Ú')
      // Acento grave (`)
      .replace(/`a/g, 'à')
      .replace(/`e/g, 'è')
      .replace(/`i/g, 'ì')
      .replace(/`o/g, 'ò')
      .replace(/`u/g, 'ù')
      .replace(/`A/g, 'À')
      .replace(/`E/g, 'È')
      .replace(/`I/g, 'Ì')
      .replace(/`O/g, 'Ò')
      .replace(/`U/g, 'Ù')
      // Circunflejo (^)
      .replace(/\^a/g, 'â')
      .replace(/\^e/g, 'ê')
      .replace(/\^i/g, 'î')
      .replace(/\^o/g, 'ô')
      .replace(/\^u/g, 'û')
      .replace(/\^A/g, 'Â')
      .replace(/\^E/g, 'Ê')
      .replace(/\^I/g, 'Î')
      .replace(/\^O/g, 'Ô')
      .replace(/\^U/g, 'Û')
      // Tilde (~)
      .replace(/~a/g, 'ã')
      .replace(/~o/g, 'õ')
      .replace(/~A/g, 'Ã')
      .replace(/~O/g, 'Õ')
      // Umlaut (¨)
      .replace(/¨a/g, 'ä')
      .replace(/¨e/g, 'ë')
      .replace(/¨i/g, 'ï')
      .replace(/¨o/g, 'ö')
      .replace(/¨u/g, 'ü')
      .replace(/¨A/g, 'Ä')
      .replace(/¨E/g, 'Ë')
      .replace(/¨I/g, 'Ï')
      .replace(/¨O/g, 'Ö')
      .replace(/¨U/g, 'Ü');
  };
  